# Generated by Django 5.2.9 on 2026-06-02 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0004_rename_iam_orgunit_parent_type_name_idx_iam_orgunit_parent__f0840d_idx'),
        ('nomina', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payrollsheet',
            name='ix_nom_sheet_p_a',
        ),
        migrations.RemoveField(
            model_name='payrollsheet',
            name='area',
        ),
        migrations.RemoveField(
            model_name='payrollsheet',
            name='area_description',
        ),
        migrations.AddField(
            model_name='payrollsheet',
            name='sheet_name',
            field=models.CharField(blank=True, default='', help_text="Nombre de la planilla (ej: 'Planilla Finca Abisinia', 'Comisariato Santa Isabel')", max_length=160),
        ),
        migrations.AlterField(
            model_name='payrollsheet',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Empresa o sucursal que genera esta planilla', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_sheets_branch', to='iam.orgunit'),
        ),
        migrations.AddIndex(
            model_name='payrollsheet',
            index=models.Index(fields=['period', 'has_inss'], name='ix_nom_sheet_p_inss'),
        ),
        migrations.AddIndex(
            model_name='payrollsheet',
            index=models.Index(fields=['branch', 'period'], name='ix_nom_sheet_br_p'),
        ),
    ]
