# Generated by Django 5.2.9 on 2026-06-02 22:14

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0004_rename_iam_orgunit_parent_type_name_idx_iam_orgunit_parent__f0840d_idx'),
        ('nomina', '0002_remove_payrollsheet_ix_nom_sheet_p_a_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NominaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.PositiveSmallIntegerField(db_index=True, help_text='Año fiscal vigente')),
                ('effective_from', models.DateField(db_index=True, help_text='Fecha desde la que aplica esta configuración')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('inss_laboral_rate', models.DecimalField(decimal_places=5, default=Decimal('0.07'), help_text='Tasa INSS laboral (ej. 0.07000 = 7%)', max_digits=6)),
                ('inss_patronal_rate_small', models.DecimalField(decimal_places=5, default=Decimal('0.215'), help_text='INSS patronal para empresas < umbral de trabajadores (ej. 0.21500 = 21.5%)', max_digits=6)),
                ('inss_patronal_rate_large', models.DecimalField(decimal_places=5, default=Decimal('0.225'), help_text='INSS patronal para empresas >= umbral de trabajadores (ej. 0.22500 = 22.5%)', max_digits=6)),
                ('inss_size_threshold', models.PositiveSmallIntegerField(default=50, help_text="Número de trabajadores a partir del cual aplica la tasa 'large'")),
                ('inatec_rate', models.DecimalField(decimal_places=5, default=Decimal('0.02'), help_text='Tasa INATEC (ej. 0.02000 = 2%)', max_digits=6)),
                ('vacation_rate', models.DecimalField(decimal_places=6, default=Decimal('0.083333'), help_text='Tasa provisión vacaciones mensual (ej. 0.083333 = 8.33%)', max_digits=8)),
                ('thirteenth_month_rate', models.DecimalField(decimal_places=6, default=Decimal('0.083333'), help_text='Tasa provisión 13vo mes mensual (ej. 0.083333 = 8.33%)', max_digits=8)),
                ('overtime_rate', models.DecimalField(decimal_places=2, default=Decimal('2.0'), help_text='Multiplicador horas extra sobre tarifa hora (ej. 2.00 = doble)', max_digits=5)),
                ('sunday_bonus_rate', models.DecimalField(decimal_places=2, default=Decimal('2.0'), help_text='Multiplicador domingos laborados (ej. 2.00 = doble)', max_digits=5)),
                ('seventh_day_rate', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Multiplicador 7mo día de descanso (ej. 1.00 = salario normal)', max_digits=5)),
                ('subsidy_employer_days', models.PositiveSmallIntegerField(default=3, help_text='Días de enfermedad que paga la empresa al 100% (antes de aplicar INSS)')),
                ('subsidy_inss_rate', models.DecimalField(decimal_places=4, default=Decimal('0.60'), help_text='Porcentaje que paga el INSS desde el día N+1 (ej. 0.6000 = 60%)', max_digits=5)),
                ('min_wage_agro', models.DecimalField(decimal_places=2, default=Decimal('6188.02'), help_text='Salario mínimo sector agropecuario (C$/mes)', max_digits=12)),
                ('min_wage_general', models.DecimalField(decimal_places=2, default=Decimal('7000.00'), help_text='Salario mínimo sector servicios/general (C$/mes)', max_digits=12)),
                ('payment_deadline_days', models.PositiveSmallIntegerField(default=10, help_text='Días hábiles del mes siguiente para pagar al INSS')),
                ('late_payment_surcharge', models.DecimalField(decimal_places=4, default=Decimal('0.03'), help_text='Recargo por mora (ej. 0.0300 = 3%)', max_digits=5)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nomina_configs', to='iam.orgunit')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nomina_configs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='IRBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(help_text='Orden del tramo (1, 2, 3...)')),
                ('min_income', models.DecimalField(decimal_places=2, help_text='Ingreso anual mínimo de este tramo (C$)', max_digits=14)),
                ('max_income', models.DecimalField(blank=True, decimal_places=2, help_text='Ingreso anual máximo (null = sin límite superior)', max_digits=14, null=True)),
                ('base_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Impuesto fijo del tramo (C$)', max_digits=14)),
                ('rate', models.DecimalField(decimal_places=5, default=Decimal('0.00'), help_text='Tasa marginal sobre el exceso (ej. 0.15000 = 15%)', max_digits=6)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ir_brackets', to='nomina.nominaconfig')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='nominaconfig',
            index=models.Index(fields=['company', 'fiscal_year', 'is_active'], name='ix_nomcfg_c_y_a'),
        ),
        migrations.AddConstraint(
            model_name='nominaconfig',
            constraint=models.UniqueConstraint(fields=('company', 'fiscal_year', 'effective_from'), name='uq_nomina_config_company_year_date'),
        ),
        migrations.AddConstraint(
            model_name='irbracket',
            constraint=models.UniqueConstraint(fields=('config', 'order'), name='uq_irbracket_config_order'),
        ),
    ]
