# Generated by Django 5.2.12 on 2026-06-06 00:28

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_employee_party'),
        ('iam', '0005_approvalrequest'),
        ('nomina', '0003_nominaconfig_irbracket_nominaconfig_ix_nomcfg_c_y_a_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollentry',
            name='payment_frequency',
            field=models.CharField(choices=[('FIRST_HALF', 'Primera quincena (1-15)'), ('SECOND_HALF', 'Segunda quincena (16-fin)'), ('CATORCENA', 'Catorcena'), ('MONTHLY', 'Mensual')], default='FIRST_HALF', max_length=12),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='period_type',
            field=models.CharField(choices=[('FIRST_HALF', 'Primera quincena (1-15)'), ('SECOND_HALF', 'Segunda quincena (16-fin)'), ('CATORCENA', 'Catorcena'), ('MONTHLY', 'Mensual')], max_length=16),
        ),
        migrations.CreateModel(
            name='FieldCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supervisor_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_crews_supervised', to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='FieldCrewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('SUBMITTED', 'Enviado'), ('RETURNED_FOR_CORRECTION', 'Devuelto'), ('REVIEWED', 'Revisado'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], db_index=True, default='DRAFT', max_length=24)),
                ('labor_code', models.CharField(blank=True, default='', max_length=64)),
                ('labor_name', models.CharField(blank=True, default='', max_length=160)),
                ('zone_label', models.CharField(blank=True, default='', max_length=160)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crew', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='report', to='nomina.fieldcrew')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_crew_reports_reviewed', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_crew_reports_submitted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FieldCrewReportLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('PRESENT', 'Presente'), ('ABSENT', 'Ausente'), ('SICK', 'Enfermo'), ('ACCIDENT', 'Accidente'), ('TRANSFERRED', 'Trasladado'), ('PERMISSION', 'Permiso'), ('LEFT_EARLY', 'Salio temprano'), ('JOINED_LATE', 'Ingreso tarde'), ('DISMISSED', 'Despedido'), ('OTHER', 'Otro')], db_index=True, default='PRESENT', max_length=16)),
                ('day_value', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_crew_report_lines', to='hr.employee')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='nomina.fieldcrewreport')),
            ],
        ),
        migrations.CreateModel(
            name='FieldRollCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_rollcalls_submitted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FieldRollCallLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Presente'), ('ABSENT', 'Ausente'), ('UNKNOWN', 'No confirmado')], db_index=True, default='UNKNOWN', max_length=12)),
                ('absence_reason', models.CharField(blank=True, default='', max_length=64)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_rollcall_lines', to='hr.employee')),
                ('rollcall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='nomina.fieldrollcall')),
            ],
        ),
        migrations.CreateModel(
            name='FieldWorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('OPEN', 'Abierto'), ('ROLLCALL_SUBMITTED', 'Lista enviada'), ('CREW_REPORTS_PENDING', 'Reportes pendientes'), ('IN_REVIEW', 'En revision'), ('APPROVED', 'Aprobado'), ('LOCKED', 'Bloqueado')], db_index=True, default='OPEN', max_length=24)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_work_days_approved', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='field_work_days_branch', to='iam.orgunit')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_work_days_company', to='iam.orgunit')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_work_days_opened', to=settings.AUTH_USER_MODEL)),
                ('payroll_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='field_work_days', to='nomina.payrollperiod')),
            ],
        ),
        migrations.CreateModel(
            name='FieldTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('transferred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_transfers_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_transfers', to='hr.employee')),
                ('from_crew', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='nomina.fieldcrew')),
                ('to_crew', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='nomina.fieldcrew')),
                ('work_day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='nomina.fieldworkday')),
            ],
        ),
        migrations.AddField(
            model_name='fieldrollcall',
            name='work_day',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='rollcall', to='nomina.fieldworkday'),
        ),
        migrations.AddField(
            model_name='fieldcrew',
            name='work_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crews', to='nomina.fieldworkday'),
        ),
        migrations.CreateModel(
            name='FieldAttendanceConsolidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OK', 'OK'), ('WARNING', 'Advertencia'), ('CONFLICT', 'Conflicto'), ('BLOCKED', 'Bloqueado'), ('APPROVED', 'Aprobado'), ('LOCKED_FOR_PAYROLL', 'Bloqueado para nomina')], db_index=True, default='OK', max_length=24)),
                ('day_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('primary_event_type', models.CharField(blank=True, choices=[('PRESENT', 'Presente'), ('ABSENT', 'Ausente'), ('SICK', 'Enfermo'), ('ACCIDENT', 'Accidente'), ('TRANSFERRED', 'Trasladado'), ('PERMISSION', 'Permiso'), ('LEFT_EARLY', 'Salio temprano'), ('JOINED_LATE', 'Ingreso tarde'), ('DISMISSED', 'Despedido'), ('OTHER', 'Otro')], default='', max_length=16)),
                ('conflict_codes', models.JSONField(blank=True, default=list)),
                ('source_summary', models.JSONField(blank=True, default=dict)),
                ('has_inss_snapshot', models.BooleanField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_consolidations_approved', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_attendance_consolidations', to='hr.employee')),
                ('payroll_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='field_attendance_consolidations', to='nomina.payrollperiod')),
                ('work_day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consolidations', to='nomina.fieldworkday')),
            ],
        ),
        migrations.CreateModel(
            name='FieldWorkerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('PRESENT', 'Presente'), ('ABSENT', 'Ausente'), ('SICK', 'Enfermo'), ('ACCIDENT', 'Accidente'), ('TRANSFERRED', 'Trasladado'), ('PERMISSION', 'Permiso'), ('LEFT_EARLY', 'Salio temprano'), ('JOINED_LATE', 'Ingreso tarde'), ('DISMISSED', 'Despedido'), ('OTHER', 'Otro')], db_index=True, max_length=16)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_worker_events_created', to=settings.AUTH_USER_MODEL)),
                ('crew_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='worker_events', to='nomina.fieldcrewreport')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_worker_events', to='hr.employee')),
                ('work_day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worker_events', to='nomina.fieldworkday')),
            ],
        ),
        migrations.AddIndex(
            model_name='fieldcrewreport',
            index=models.Index(fields=['status'], name='ix_fcr_status'),
        ),
        migrations.AddIndex(
            model_name='fieldcrewreport',
            index=models.Index(fields=['submitted_by', 'submitted_at'], name='ix_fcr_submitter_at'),
        ),
        migrations.AddIndex(
            model_name='fieldcrewreportline',
            index=models.Index(fields=['employee', 'event_type'], name='ix_fcrl_emp_event'),
        ),
        migrations.AddConstraint(
            model_name='fieldcrewreportline',
            constraint=models.UniqueConstraint(fields=('report', 'employee'), name='uq_fcrl_report_employee'),
        ),
        migrations.AddConstraint(
            model_name='fieldcrewreportline',
            constraint=models.CheckConstraint(condition=models.Q(('day_value__gte', 0), ('day_value__lte', 1)), name='ck_fcrl_day_value_range'),
        ),
        migrations.AddIndex(
            model_name='fieldrollcallline',
            index=models.Index(fields=['employee', 'status'], name='ix_frl_employee_status'),
        ),
        migrations.AddConstraint(
            model_name='fieldrollcallline',
            constraint=models.UniqueConstraint(fields=('rollcall', 'employee'), name='uq_frl_rollcall_employee'),
        ),
        migrations.AddIndex(
            model_name='fieldworkday',
            index=models.Index(fields=['company', 'branch', 'work_date'], name='ix_fwd_c_b_date'),
        ),
        migrations.AddIndex(
            model_name='fieldworkday',
            index=models.Index(fields=['company', 'status'], name='ix_fwd_c_status'),
        ),
        migrations.AddIndex(
            model_name='fieldworkday',
            index=models.Index(fields=['payroll_period', 'status'], name='ix_fwd_period_status'),
        ),
        migrations.AddConstraint(
            model_name='fieldworkday',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', True)), fields=('company', 'work_date'), name='uq_fwd_c_date_null_branch'),
        ),
        migrations.AddConstraint(
            model_name='fieldworkday',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', False)), fields=('company', 'branch', 'work_date'), name='uq_fwd_c_branch_date'),
        ),
        migrations.AddIndex(
            model_name='fieldtransfer',
            index=models.Index(fields=['work_day', 'employee'], name='ix_ft_workday_employee'),
        ),
        migrations.AddConstraint(
            model_name='fieldtransfer',
            constraint=models.CheckConstraint(condition=models.Q(('from_crew', models.F('to_crew')), _negated=True), name='ck_ft_different_crews'),
        ),
        migrations.AddIndex(
            model_name='fieldrollcall',
            index=models.Index(fields=['submitted_by', 'submitted_at'], name='ix_frc_submitter_at'),
        ),
        migrations.AddIndex(
            model_name='fieldcrew',
            index=models.Index(fields=['work_day', 'supervisor_employee'], name='ix_fc_workday_supervisor'),
        ),
        migrations.AddConstraint(
            model_name='fieldcrew',
            constraint=models.UniqueConstraint(fields=('work_day', 'name'), name='uq_fc_workday_name'),
        ),
        migrations.AddIndex(
            model_name='fieldattendanceconsolidation',
            index=models.Index(fields=['work_day', 'status'], name='ix_fac_workday_status'),
        ),
        migrations.AddIndex(
            model_name='fieldattendanceconsolidation',
            index=models.Index(fields=['employee', 'status'], name='ix_fac_employee_status'),
        ),
        migrations.AddConstraint(
            model_name='fieldattendanceconsolidation',
            constraint=models.UniqueConstraint(fields=('work_day', 'employee'), name='uq_fac_workday_employee'),
        ),
        migrations.AddConstraint(
            model_name='fieldattendanceconsolidation',
            constraint=models.CheckConstraint(condition=models.Q(('day_value__gte', 0), ('day_value__lte', 1)), name='ck_fac_day_value_range'),
        ),
        migrations.AddIndex(
            model_name='fieldworkerevent',
            index=models.Index(fields=['work_day', 'employee'], name='ix_fwe_workday_employee'),
        ),
        migrations.AddIndex(
            model_name='fieldworkerevent',
            index=models.Index(fields=['event_type'], name='ix_fwe_type'),
        ),
    ]
