# Generated by Django 5.2.12 on 2026-06-07 01:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_employee_party'),
        ('iam', '0005_approvalrequest'),
        ('nomina', '0004_alter_payrollentry_payment_frequency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInssEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regime', models.CharField(choices=[('AFFILIATED', 'Cotiza INSS'), ('NOT_AFFILIATED', 'No cotiza INSS')], default='AFFILIATED', max_length=16)),
                ('effective_from', models.DateField(db_index=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inss_enrollments_company', to='iam.orgunit')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inss_enrollments_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inss_enrollments', to='hr.employee')),
            ],
            options={
                'indexes': [models.Index(fields=['employee', 'effective_from'], name='ix_inss_enroll_emp_from'), models.Index(fields=['company', 'regime'], name='ix_inss_enroll_c_regime')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'effective_from'), name='uq_inss_enroll_emp_from')],
            },
        ),
        migrations.CreateModel(
            name='PayrollInssElection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(blank=True, default='', max_length=20)),
                ('elected_has_inss', models.BooleanField()),
                ('source', models.CharField(choices=[('ENROLLMENT', 'Desde afiliación'), ('OVERRIDE', 'Override del período')], default='ENROLLMENT', max_length=16)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inss_elections_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inss_elections', to='hr.employee')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inss_elections', to='nomina.payrollperiod')),
            ],
            options={
                'indexes': [models.Index(fields=['period', 'source'], name='ix_inss_elec_period_src')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('employee__isnull', False)), fields=('period', 'employee'), name='uq_inss_election_period_emp'), models.UniqueConstraint(condition=models.Q(('employee__isnull', True), models.Q(('cedula', ''), _negated=True)), fields=('period', 'cedula'), name='uq_inss_election_period_cedula')],
            },
        ),
    ]
