# Generated by Django 5.2.12 on 2026-06-07 15:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0005_employeeinssenrollment_payrollinsselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominaconfig',
            name='holiday_worked_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.0'), help_text='Multiplicador feriado laborado (ej. 2.00 = doble)', max_digits=5),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='holiday_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='holiday_worked_days',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Días feriados laborados', max_digits=5),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='seventh_day_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='seventh_day_days',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Séptimos días ganados (1 por semana completa; jornaleros DAILY)', max_digits=5),
        ),
    ]
