# Generated by Django 5.2.12 on 2026-06-07 20:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0005_approvalrequest'),
        ('nomina', '0006_nominaconfig_holiday_worked_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', help_text='Identificador estable (slug) para precarga idempotente y referencia.', max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('legal_type', models.CharField(choices=[('NACIONAL_OBLIGATORIO', 'Nacional obligatorio (Código del Trabajo)'), ('ASUETO_ESTATAL', 'Asueto estatal (sector público)'), ('LOCAL', 'Local / fiesta patronal'), ('EMPRESA', 'De empresa')], max_length=24)),
                ('date_kind', models.CharField(choices=[('FIXED', 'Fija (mes/día, todos los años)'), ('EASTER', 'Móvil (offset de días respecto a Pascua)'), ('ONE_OFF', 'Puntual (fecha exacta de un año)')], max_length=8)),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('easter_offset', models.SmallIntegerField(blank=True, null=True)),
                ('specific_date', models.DateField(blank=True, null=True)),
                ('locality', models.CharField(blank=True, default='', help_text="Etiqueta geográfica informativa (general). P.ej. 'Nacional', 'Managua'.", max_length=120)),
                ('applies_to_payroll', models.BooleanField(default=True, help_text='Si por defecto cuenta para la planilla. Asuetos estatales = False.')),
                ('pays_premium', models.BooleanField(default=True, help_text='Si laborado paga prima (doble). Feriado obligatorio = True.')),
                ('premium_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Multiplicador del día si se labora. NULL = usar NominaConfig.holiday_worked_rate.', max_digits=5, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, help_text='NULL = catálogo nacional compartido; no-NULL = feriado propio de la empresa.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='iam.orgunit')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'is_active'], name='ix_holiday_company_active'), models.Index(fields=['date_kind'], name='ix_holiday_date_kind')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('company', 'code'), name='uq_holiday_company_code'), models.CheckConstraint(condition=models.Q(('month__isnull', True), models.Q(('month__gte', 1), ('month__lte', 12)), _connector='OR'), name='ck_holiday_month_range'), models.CheckConstraint(condition=models.Q(('day__isnull', True), models.Q(('day__gte', 1), ('day__lte', 31)), _connector='OR'), name='ck_holiday_day_range')],
            },
        ),
    ]
