# Generated by Django 5.2.12 on 2026-06-07 21:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_employee_party'),
        ('iam', '0005_approvalrequest'),
        ('nomina', '0008_seed_nicaragua_holidays'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancereport',
            name='source',
            field=models.CharField(choices=[('BIOMETRIC', 'Control biométrico'), ('SUPERVISOR_APP', 'Reporte jefe de área (app)'), ('PAYROLL_REVIEW', 'Revisión encargado de nómina'), ('MANUAL', 'Manual (eventualidad)'), ('FIELD', 'Asistencia de campo consolidada')], db_index=True, max_length=20),
        ),
        migrations.AddConstraint(
            model_name='attendancereport',
            constraint=models.UniqueConstraint(condition=models.Q(('employee__isnull', False)), fields=('period', 'employee', 'source'), name='uq_attreport_period_emp_source'),
        ),
    ]
