# Generated by Django 5.2.12 on 2026-06-06 00:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_employee_party'),
        ('iam', '0005_approvalrequest'),
        ('nomina', '0009_alter_attendancereport_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(blank=True, default='', max_length=64)),
                ('name', models.CharField(max_length=160)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nomina_field_crews_branch', to='iam.orgunit')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nomina_field_crews_company', to='iam.orgunit')),
                ('foreman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='field_crews_led', to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='CrewMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_from', models.DateField(default=django.utils.timezone.localdate)),
                ('active_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='nomina.crew')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_crew_memberships', to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='FieldCaptureWorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_day_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('work_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('SUBMITTED', 'Enviado'), ('APPROVAL_PENDING', 'Aprobación pendiente'), ('APPROVED', 'Aprobado')], db_index=True, default='DRAFT', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nomina_field_work_days_branch', to='iam.orgunit')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nomina_field_work_days_company', to='iam.orgunit')),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_days', to='nomina.crew')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_capture_work_days', to='nomina.payrollperiod')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_capture_work_days_submitted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FieldCaptureReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('SUBMITTED', 'Enviado'), ('APPROVAL_PENDING', 'Aprobación pendiente'), ('APPROVED', 'Aprobado')], db_index=True, default='DRAFT', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='field_capture_reports', to='iam.approvalrequest')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_capture_reports_approved', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nomina_field_reports_branch', to='iam.orgunit')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nomina_field_reports_company', to='iam.orgunit')),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_reports', to='nomina.crew')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_capture_reports', to='nomina.payrollperiod')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_capture_reports_reported', to=settings.AUTH_USER_MODEL)),
                ('work_day', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='crew_report', to='nomina.fieldcaptureworkday')),
            ],
        ),
        migrations.CreateModel(
            name='FieldCaptureEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('cedula', models.CharField(blank=True, default='', max_length=20)),
                ('employee_name', models.CharField(blank=True, default='', max_length=160)),
                ('event_type', models.CharField(choices=[('PRESENT', 'Presente'), ('ABSENT', 'Ausente'), ('SICK', 'Enfermo'), ('SUBSIDY', 'Subsidio INSS'), ('ACCIDENT', 'Accidente laboral'), ('TRANSFER', 'Traslado'), ('VACATION', 'Vacaciones')], db_index=True, max_length=16)),
                ('day_value', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('sunday_worked_days', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nomina_field_events_branch', to='iam.orgunit')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nomina_field_events_company', to='iam.orgunit')),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worker_events', to='nomina.crew')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='field_capture_events', to='hr.employee')),
                ('from_crew', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='worker_events_transferred_from', to='nomina.crew')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_capture_events', to='nomina.payrollperiod')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_capture_events_recorded', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worker_events', to='nomina.fieldcapturereport')),
                ('to_crew', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='worker_events_transferred_to', to='nomina.crew')),
                ('work_day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worker_events', to='nomina.fieldcaptureworkday')),
            ],
        ),
        migrations.AddIndex(
            model_name='crew',
            index=models.Index(fields=['company', 'is_active'], name='ix_nom_field_crew_c_a'),
        ),
        migrations.AddIndex(
            model_name='crew',
            index=models.Index(fields=['branch', 'is_active'], name='ix_nom_field_crew_b_a'),
        ),
        migrations.AddConstraint(
            model_name='crew',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uq_nom_field_crew_company_name'),
        ),
        migrations.AddIndex(
            model_name='crewmembership',
            index=models.Index(fields=['crew', 'is_active'], name='ix_nom_field_member_crew_a'),
        ),
        migrations.AddIndex(
            model_name='crewmembership',
            index=models.Index(fields=['employee', 'is_active'], name='ix_nom_field_member_emp_a'),
        ),
        migrations.AddConstraint(
            model_name='crewmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('crew', 'employee'), name='uq_nom_field_membership_active'),
        ),
        migrations.AddIndex(
            model_name='fieldcaptureworkday',
            index=models.Index(fields=['company', 'work_date'], name='ix_nom_field_workday_c_d'),
        ),
        migrations.AddIndex(
            model_name='fieldcaptureworkday',
            index=models.Index(fields=['period', 'status'], name='ix_nom_field_workday_p_st'),
        ),
        migrations.AddIndex(
            model_name='fieldcaptureworkday',
            index=models.Index(fields=['crew', 'status'], name='ix_nom_field_workday_crew_st'),
        ),
        migrations.AddConstraint(
            model_name='fieldcaptureworkday',
            constraint=models.UniqueConstraint(fields=('crew', 'work_date'), name='uq_nom_field_workday_crew_date'),
        ),
        migrations.AddIndex(
            model_name='fieldcapturereport',
            index=models.Index(fields=['company', 'status'], name='ix_nom_field_report_c_st'),
        ),
        migrations.AddIndex(
            model_name='fieldcapturereport',
            index=models.Index(fields=['period', 'status'], name='ix_nom_field_report_p_st'),
        ),
        migrations.AddIndex(
            model_name='fieldcapturereport',
            index=models.Index(fields=['crew', 'status'], name='ix_nom_field_report_crew_st'),
        ),
        migrations.AddIndex(
            model_name='fieldcaptureevent',
            index=models.Index(fields=['company', 'event_type'], name='ix_nom_field_event_c_type'),
        ),
        migrations.AddIndex(
            model_name='fieldcaptureevent',
            index=models.Index(fields=['work_day', 'event_type'], name='ix_nom_field_event_day_type'),
        ),
        migrations.AddIndex(
            model_name='fieldcaptureevent',
            index=models.Index(fields=['employee', 'period'], name='ix_nom_field_event_emp_p'),
        ),
        migrations.AddIndex(
            model_name='fieldcaptureevent',
            index=models.Index(fields=['cedula', 'period'], name='ix_nom_field_event_ced_p'),
        ),
        migrations.AddConstraint(
            model_name='fieldcaptureevent',
            constraint=models.CheckConstraint(condition=models.Q(('day_value__gte', 0)), name='ck_nom_field_event_day_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='fieldcaptureevent',
            constraint=models.UniqueConstraint(condition=models.Q(('employee__isnull', False)), fields=('report', 'employee', 'event_type'), name='uq_nom_field_event_emp_type'),
        ),
        migrations.AddConstraint(
            model_name='fieldcaptureevent',
            constraint=models.UniqueConstraint(condition=models.Q(('employee__isnull', True), models.Q(('cedula', ''), _negated=True)), fields=('report', 'cedula', 'event_type'), name='uq_nom_field_event_ced_type'),
        ),
    ]
