# Generated by Django 5.2.12 on 2026-06-09 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0010_field_capture_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollentry',
            name='ir_manual',
            field=models.BooleanField(default=False, help_text='IR fijado manualmente (override): si True, compute_all NO recalcula el IR.'),
        ),
    ]
