# Generated by Django 5.2.12 on 2026-06-09 03:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0011_payrollentry_ir_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollloandeduction',
            name='abono_applied',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
    ]
