# Generated by Django 5.2.12 on 2026-06-11 01:13

import apps.kernels.nomina.biometric.models_biometric
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_employeelifecycleevent_employeememo_and_more'),
        ('iam', '0005_approvalrequest'),
        ('nomina', '0012_payrollloandeduction_abono_applied'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('vendor', models.CharField(blank=True, default='', max_length=120)),
                ('serial', models.CharField(blank=True, default='', max_length=120)),
                ('api_token', models.CharField(default=apps.kernels.nomina.biometric.models_biometric.new_device_token, editable=False, max_length=64, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nomina_biometric_devices_branch', to='iam.orgunit')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nomina_biometric_devices_company', to='iam.orgunit')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nomina_biometric_devices_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BiometricImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('rows_total', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('unmatched_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nomina_biometric_batches_company', to='iam.orgunit')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='nomina.biometricdevice')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nomina_biometric_batches_imported', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BiometricCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_code', models.CharField(db_index=True, max_length=64)),
                ('external_name', models.CharField(blank=True, default='', max_length=160)),
                ('direction', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida'), ('UNKNOWN', 'Sin dirección')], default='UNKNOWN', max_length=8)),
                ('checked_at', models.DateTimeField(db_index=True)),
                ('work_date', models.DateField(db_index=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('dedupe_key', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nomina_biometric_checks_company', to='iam.orgunit')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_checks', to='hr.employee')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checks', to='nomina.biometricdevice')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checks', to='nomina.biometricimportbatch')),
            ],
            options={
                'ordering': ['-checked_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BiometricPersonMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_code', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nomina_biometric_maps_company', to='iam.orgunit')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nomina_biometric_maps_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_maps', to='hr.employee')),
            ],
        ),
        migrations.AddIndex(
            model_name='biometricdevice',
            index=models.Index(fields=['company', 'is_active'], name='nomina_biom_company_d29ab3_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricimportbatch',
            index=models.Index(fields=['company', 'created_at'], name='nomina_biom_company_631bb2_idx'),
        ),
        migrations.AddIndex(
            model_name='biometriccheck',
            index=models.Index(fields=['company', 'work_date'], name='nomina_biom_company_d3e096_idx'),
        ),
        migrations.AddIndex(
            model_name='biometriccheck',
            index=models.Index(fields=['employee', 'work_date'], name='nomina_biom_employe_3abdab_idx'),
        ),
        migrations.AddIndex(
            model_name='biometriccheck',
            index=models.Index(fields=['company', 'external_code'], name='nomina_biom_company_9cf116_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricpersonmap',
            index=models.Index(fields=['company', 'is_active'], name='nomina_biom_company_f0c5a2_idx'),
        ),
        migrations.AddConstraint(
            model_name='biometricpersonmap',
            constraint=models.UniqueConstraint(fields=('company', 'external_code'), name='uq_biometric_map_company_code'),
        ),
    ]
