# Generated by Django 5.2.12 on 2026-03-25 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_role_permission_active_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='permission',
            new_name='rbac_permis_is_acti_42ab9f_idx',
            old_name='rbac_perm_active_code_idx',
        ),
        migrations.RenameIndex(
            model_name='role',
            new_name='rbac_role_is_acti_d9ae7f_idx',
            old_name='rbac_role_active_name_idx',
        ),
    ]
