# Generated by Django 5.2.12 on 2026-06-08 17:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iam', '0005_approvalrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SegregationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('permission_a', models.CharField(max_length=128)),
                ('permission_b', models.CharField(max_length=128)),
                ('event_a', models.CharField(blank=True, default='', max_length=64)),
                ('event_b', models.CharField(blank=True, default='', max_length=64)),
                ('severity', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='HIGH', max_length=16)),
                ('rationale', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='segregation_rules', to='iam.orgunit')),
            ],
        ),
        migrations.CreateModel(
            name='ControlFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_code', models.CharField(choices=[('SOD_GRANT', 'SoD por concesión'), ('SOD_EXERCISED', 'SoD por ejercicio')], max_length=32)),
                ('severity', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='HIGH', max_length=16)),
                ('subject_type', models.CharField(blank=True, default='', max_length=32)),
                ('subject_id', models.CharField(blank=True, default='', max_length=128)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('OPEN', 'Abierto'), ('ACKNOWLEDGED', 'Reconocido'), ('RESOLVED', 'Resuelto'), ('DISMISSED', 'Descartado')], default='OPEN', max_length=16)),
                ('dedup_key', models.CharField(max_length=200)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_findings', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='control_findings', to='iam.orgunit')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_findings_resolved', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='controls.segregationrule')),
            ],
        ),
        migrations.AddIndex(
            model_name='segregationrule',
            index=models.Index(fields=['company', 'is_active'], name='controls_se_company_37aea3_idx'),
        ),
        migrations.AddConstraint(
            model_name='segregationrule',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uq_segrule_company_code'),
        ),
        migrations.AddConstraint(
            model_name='segregationrule',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', True)), fields=('code',), name='uq_segrule_global_code'),
        ),
        migrations.AddIndex(
            model_name='controlfinding',
            index=models.Index(fields=['company', 'status', '-detected_at'], name='controls_co_company_d3c9d5_idx'),
        ),
        migrations.AddIndex(
            model_name='controlfinding',
            index=models.Index(fields=['company', 'control_code', 'status'], name='controls_co_company_b3e7e9_idx'),
        ),
        migrations.AddIndex(
            model_name='controlfinding',
            index=models.Index(fields=['actor_user', '-detected_at'], name='controls_co_actor_u_cce1ff_idx'),
        ),
        migrations.AddConstraint(
            model_name='controlfinding',
            constraint=models.UniqueConstraint(fields=('company', 'dedup_key'), name='uq_finding_company_dedup'),
        ),
    ]
