# Generated by Django 5.2.12 on 2026-03-25 16:21

from django.conf import settings
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('accounting', '0009_rename_acc_coa_comp_type_act_idx_accounting__company_41d161_idx_and_more'),
        ('iam', '0004_rename_iam_orgunit_parent_type_name_idx_iam_orgunit_parent__f0840d_idx'),
        ('inventarios', '0002_stockmovement_accounting_links'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventoryitem',
            name='uniq_inv_sku_per_company',
        ),
        migrations.RemoveConstraint(
            model_name='stockbalance',
            name='uniq_inv_balance_per_scope',
        ),
        migrations.RemoveConstraint(
            model_name='stockmovement',
            name='uniq_inv_idempotency_per_company',
        ),
        migrations.RemoveConstraint(
            model_name='warehouse',
            name='uniq_inv_wh_code_per_branch',
        ),
        migrations.RenameIndex(
            model_name='inventoryitem',
            new_name='ix_invitm_c_as',
            old_name='inventarios_company_is_active_sku_idx',
        ),
        migrations.RenameIndex(
            model_name='warehouse',
            new_name='ix_invwh_c_b_an',
            old_name='inventarios_company_branch_is_active_name_idx',
        ),
        AddIndexConcurrently(
            model_name='inventoryitem',
            index=models.Index(fields=['company', 'is_active', 'name'], name='ix_invitm_c_an'),
        ),
        AddIndexConcurrently(
            model_name='stockbalance',
            index=models.Index(fields=['company', 'branch', 'warehouse', 'item'], name='ix_invbal_scope'),
        ),
        AddIndexConcurrently(
            model_name='stockmovement',
            index=models.Index(fields=['company', 'branch', 'created_at'], name='ix_invmov_c_b_ca'),
        ),
        AddIndexConcurrently(
            model_name='stockmovement',
            index=models.Index(fields=['company', 'branch', 'item', 'created_at'], name='ix_invmov_item_ca'),
        ),
        AddIndexConcurrently(
            model_name='stockmovement',
            index=models.Index(fields=['company', 'branch', 'warehouse', 'created_at'], name='ix_invmov_wh_ca'),
        ),
        AddIndexConcurrently(
            model_name='stockmovement',
            index=models.Index(fields=['company', 'idempotency_key'], name='ix_invmov_idem'),
        ),
        AddIndexConcurrently(
            model_name='warehouse',
            index=models.Index(fields=['company', 'branch', 'code'], name='ix_invwh_c_b_code'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(fields=('company', 'sku'), name='uniq_inv_sku_pc'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.UniqueConstraint(fields=('company', 'branch', 'warehouse', 'item'), name='uniq_inv_bal_scope'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('company', 'idempotency_key'), name='uniq_invmov_idem'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('company', 'branch', 'code'), name='uniq_inv_wh_code_pb'),
        ),
    ]
