# Generated by Django 5.2.9 on 2026-06-02 19:09

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_posting_ruleset_rule_family'),
        ('iam', '0004_rename_iam_orgunit_parent_type_name_idx_iam_orgunit_parent__f0840d_idx'),
        ('inventarios', '0003_remove_inventoryitem_uniq_inv_sku_per_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(db_index=True, max_length=80)),
                ('supplier_lot_ref', models.CharField(blank=True, default='', max_length=80)),
                ('production_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('QUARANTINE', 'Cuarentena'), ('EXPIRED', 'Vencido'), ('RECALLED', 'Recall / Devuelto'), ('EXHAUSTED', 'Agotado')], db_index=True, default='ACTIVE', max_length=16)),
                ('quarantine_reason', models.CharField(blank=True, default='', max_length=255)),
                ('qty_received', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LotBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_on_hand', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('avg_cost', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=18)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='warehouse',
            name='uniq_inv_wh_code_pb',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='barcode',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inv_items_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='is_controlled',
            field=models.BooleanField(default=False, help_text='Agroquímico u otro insumo que requiere registro especial'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='max_stock_qty',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Capacidad máxima; null = sin límite', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='min_stock_qty',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='purchase_uom',
            field=models.CharField(blank=True, choices=[('UNIT', 'Unidad'), ('DOZEN', 'Docena'), ('PACK', 'Paquete'), ('BOX', 'Caja'), ('GRAM', 'Gramo'), ('KILOGRAM', 'Kilogramo'), ('POUND', 'Libra'), ('QUINTAL', 'Quintal (100 lb)'), ('TON', 'Tonelada Métrica'), ('MILLILITER', 'Mililitro'), ('LITER', 'Litro'), ('GALLON', 'Galón'), ('BARREL', 'Barril'), ('METER', 'Metro'), ('SQUARE_METER', 'Metro Cuadrado'), ('MANZANA', 'Manzana'), ('HOUR', 'Hora'), ('DAY', 'Día'), ('GOLD_QUINTAL', 'Quintal Oro'), ('WET_QUINTAL', 'Quintal Húmedo'), ('DRY_QUINTAL', 'Quintal Seco')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='purchase_uom_factor',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Cuántas unidades base equivalen a 1 unidad de compra', max_digits=14),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='reorder_point',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='sale_uom',
            field=models.CharField(blank=True, choices=[('UNIT', 'Unidad'), ('DOZEN', 'Docena'), ('PACK', 'Paquete'), ('BOX', 'Caja'), ('GRAM', 'Gramo'), ('KILOGRAM', 'Kilogramo'), ('POUND', 'Libra'), ('QUINTAL', 'Quintal (100 lb)'), ('TON', 'Tonelada Métrica'), ('MILLILITER', 'Mililitro'), ('LITER', 'Litro'), ('GALLON', 'Galón'), ('BARREL', 'Barril'), ('METER', 'Metro'), ('SQUARE_METER', 'Metro Cuadrado'), ('MANZANA', 'Manzana'), ('HOUR', 'Hora'), ('DAY', 'Día'), ('GOLD_QUINTAL', 'Quintal Oro'), ('WET_QUINTAL', 'Quintal Húmedo'), ('DRY_QUINTAL', 'Quintal Seco')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='sale_uom_factor',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Cuántas unidades base equivalen a 1 unidad de venta', max_digits=14),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='shelf_life_days',
            field=models.PositiveIntegerField(blank=True, help_text='Vida útil en días desde producción', null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='storage_condition',
            field=models.CharField(choices=[('AMBIENT', 'Ambiente'), ('REFRIGERATED', 'Refrigerado'), ('FROZEN', 'Congelado'), ('HAZMAT', 'Material Peligroso'), ('DRY', 'Seco / Ventilado')], default='AMBIENT', max_length=16),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='track_expiry',
            field=models.BooleanField(default=False, help_text='Registra fecha de vencimiento por lote'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='track_lots',
            field=models.BooleanField(default=False, help_text='Requiere número de lote en cada movimiento'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stockbalance',
            name='qty_reserved',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Cantidad reservada por órdenes pendientes', max_digits=18),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='expiry_date',
            field=models.DateField(blank=True, db_index=True, help_text='Vencimiento del lote en este movimiento (desnormalizado para queries)', null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='movement_uom',
            field=models.CharField(blank=True, choices=[('UNIT', 'Unidad'), ('DOZEN', 'Docena'), ('PACK', 'Paquete'), ('BOX', 'Caja'), ('GRAM', 'Gramo'), ('KILOGRAM', 'Kilogramo'), ('POUND', 'Libra'), ('QUINTAL', 'Quintal (100 lb)'), ('TON', 'Tonelada Métrica'), ('MILLILITER', 'Mililitro'), ('LITER', 'Litro'), ('GALLON', 'Galón'), ('BARREL', 'Barril'), ('METER', 'Metro'), ('SQUARE_METER', 'Metro Cuadrado'), ('MANZANA', 'Manzana'), ('HOUR', 'Hora'), ('DAY', 'Día'), ('GOLD_QUINTAL', 'Quintal Oro'), ('WET_QUINTAL', 'Quintal Húmedo'), ('DRY_QUINTAL', 'Quintal Seco')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='movement_uom_factor',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Factor de conversión aplicado al recibir/despachar en UoM distinta', max_digits=14),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='location_description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='warehouse_type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('AGROCHEMICAL', 'Agroquímicos'), ('COLD_STORAGE', 'Cámara Fría'), ('FINISHED_GOODS', 'Producto Terminado'), ('RAW_MATERIALS', 'Materia Prima'), ('TOOLS', 'Herramientas y Equipos'), ('FUEL', 'Combustibles'), ('TRANSIT', 'En Tránsito'), ('COFFEE', 'Café')], default='GENERAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='uom',
            field=models.CharField(choices=[('UNIT', 'Unidad'), ('DOZEN', 'Docena'), ('PACK', 'Paquete'), ('BOX', 'Caja'), ('GRAM', 'Gramo'), ('KILOGRAM', 'Kilogramo'), ('POUND', 'Libra'), ('QUINTAL', 'Quintal (100 lb)'), ('TON', 'Tonelada Métrica'), ('MILLILITER', 'Mililitro'), ('LITER', 'Litro'), ('GALLON', 'Galón'), ('BARREL', 'Barril'), ('METER', 'Metro'), ('SQUARE_METER', 'Metro Cuadrado'), ('MANZANA', 'Manzana'), ('HOUR', 'Hora'), ('DAY', 'Día'), ('GOLD_QUINTAL', 'Quintal Oro'), ('WET_QUINTAL', 'Quintal Húmedo'), ('DRY_QUINTAL', 'Quintal Seco')], default='UNIT', max_length=16),
        ),
        migrations.AlterField(
            model_name='stockbalance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('RECEIVE', 'Recepción'), ('ISSUE', 'Despacho'), ('ADJUST', 'Ajuste'), ('TRANSFER_OUT', 'Transferencia Salida'), ('TRANSFER_IN', 'Transferencia Entrada'), ('RETURN', 'Devolución a Proveedor'), ('SHRINKAGE', 'Merma / Pérdida'), ('PRODUCTION_IN', 'Entrada de Producción'), ('PRODUCTION_OUT', 'Salida a Producción'), ('PHYSICAL_COUNT', 'Conteo Físico')], db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['company', 'category', 'is_active'], name='ix_invitm_c_cat'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['company', 'barcode'], name='ix_invitm_c_bc'),
        ),
        migrations.AddIndex(
            model_name='stockbalance',
            index=models.Index(fields=['company', 'item'], name='ix_invbal_c_item'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['company', 'branch', 'warehouse_type'], name='ix_invwh_c_b_type'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode', ''), _negated=True), fields=('company', 'barcode'), name='uniq_inv_barcode_pc'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('company', 'branch', 'code'), name='uniq_inv_wh_code_pb'),
        ),
        migrations.AddField(
            model_name='itemlot',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inv_lots_company', to='iam.orgunit'),
        ),
        migrations.AddField(
            model_name='itemlot',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inv_lots_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemlot',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='inventarios.inventoryitem'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventarios.itemlot'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['company', 'branch', 'movement_type', 'created_at'], name='ix_invmov_type_ca'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['lot', 'created_at'], name='ix_invmov_lot_ca'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['expiry_date', 'movement_type'], name='ix_invmov_exp_type'),
        ),
        migrations.AddField(
            model_name='lotbalance',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inv_lotbal_branch', to='iam.orgunit'),
        ),
        migrations.AddField(
            model_name='lotbalance',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inv_lotbal_company', to='iam.orgunit'),
        ),
        migrations.AddField(
            model_name='lotbalance',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lot_balances', to='inventarios.inventoryitem'),
        ),
        migrations.AddField(
            model_name='lotbalance',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='inventarios.itemlot'),
        ),
        migrations.AddField(
            model_name='lotbalance',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lot_balances', to='inventarios.warehouse'),
        ),
        migrations.AddIndex(
            model_name='itemlot',
            index=models.Index(fields=['company', 'item', 'status'], name='ix_invlot_c_i_st'),
        ),
        migrations.AddIndex(
            model_name='itemlot',
            index=models.Index(fields=['expiry_date', 'status'], name='ix_invlot_exp_st'),
        ),
        migrations.AddConstraint(
            model_name='itemlot',
            constraint=models.UniqueConstraint(fields=('company', 'item', 'lot_number'), name='uniq_inv_lot_item_number'),
        ),
        migrations.AddIndex(
            model_name='lotbalance',
            index=models.Index(fields=['company', 'branch', 'warehouse', 'item', 'lot'], name='ix_invlotbal_scope'),
        ),
        migrations.AddIndex(
            model_name='lotbalance',
            index=models.Index(fields=['lot', 'qty_on_hand'], name='ix_invlotbal_lot_qty'),
        ),
        migrations.AddConstraint(
            model_name='lotbalance',
            constraint=models.UniqueConstraint(fields=('company', 'branch', 'warehouse', 'item', 'lot'), name='uniq_inv_lotbal_scope'),
        ),
    ]
