# Generated by Django 5.2.12 on 2026-06-03 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0004_itemlot_lotbalance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='reversal_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='inventarios.stockmovement'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
