# Generated by Django 5.2.12 on 2026-06-03 19:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0005_approvalrequest'),
        ('inventarios', '0005_stockmovement_reversal_of_stockmovement_reversed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Remision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remision_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('origin_type', models.CharField(choices=[('PURCHASE', 'Compra a proveedor'), ('INTERNAL_TRANSFER', 'Traslado inter-sucursal')], max_length=24)),
                ('source_module', models.CharField(blank=True, default='', max_length=32)),
                ('source_type', models.CharField(blank=True, default='', max_length=64)),
                ('source_id', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('DISPATCHED', 'Despachada'), ('RECEIVED', 'Recibida'), ('CANCELLED', 'Cancelada')], db_index=True, default='DRAFT', max_length=16)),
                ('has_discrepancy', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=96)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remisiones_branch', to='iam.orgunit')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remisiones_company', to='iam.orgunit')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remisiones_created', to=settings.AUTH_USER_MODEL)),
                ('dest_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remisiones_dest', to='inventarios.warehouse')),
                ('dispatched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remisiones_dispatched', to=settings.AUTH_USER_MODEL)),
                ('origin_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='remisiones_origin', to='inventarios.warehouse')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remisiones_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RemisionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('qty_dispatched', models.DecimalField(decimal_places=4, max_digits=18)),
                ('qty_received', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('unit_cost', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=18)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remision_lines', to='inventarios.inventoryitem')),
                ('received_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remision_lines', to='inventarios.stockmovement')),
                ('remision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventarios.remision')),
            ],
        ),
        migrations.CreateModel(
            name='RemisionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_ref', models.CharField(max_length=255)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('mime_type', models.CharField(blank=True, default='image/jpeg', max_length=64)),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('remision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inventarios.remision')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remision_photos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='remision',
            index=models.Index(fields=['company', 'branch', 'status', 'created_at'], name='ix_remision_scope'),
        ),
        migrations.AddIndex(
            model_name='remision',
            index=models.Index(fields=['company', 'dest_warehouse', 'status'], name='ix_remision_dest'),
        ),
        migrations.AddConstraint(
            model_name='remision',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('company', 'idempotency_key'), name='uniq_remision_idem'),
        ),
        migrations.AddIndex(
            model_name='remisionline',
            index=models.Index(fields=['remision', 'item'], name='ix_remisionline_remi_item'),
        ),
        migrations.AddIndex(
            model_name='remisionphoto',
            index=models.Index(fields=['remision', 'created_at'], name='ix_remisionphoto_remi'),
        ),
    ]
