# Generated by Django 5.2.12 on 2026-06-03 19:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0005_approvalrequest'),
        ('inventarios', '0006_remision_remisionline_remisionphoto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCostPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('WEIGHTED_AVERAGE', 'Promedio ponderado (móvil)'), ('STANDARD', 'Costo estándar'), ('FIFO', 'PEPS (primeras entradas)')], default='WEIGHTED_AVERAGE', max_length=24)),
                ('version', models.PositiveIntegerField(default=1)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_policies_branch', to='iam.orgunit')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_policies_company', to='iam.orgunit')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_policies_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'branch', 'is_active'], name='ix_cost_policy_active'), models.Index(fields=['company', 'branch', 'effective_from'], name='ix_cost_policy_eff')],
                'constraints': [models.UniqueConstraint(fields=('company', 'branch', 'version'), name='uq_cost_policy_scope_version')],
            },
        ),
    ]
