# Generated by Django 5.2.12 on 2026-06-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0007_inventorycostpolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='cost_policy_version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
