# Generated by Django 5.2.12 on 2026-06-03 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0008_stockmovement_cost_policy_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='inventory_class',
            field=models.CharField(blank=True, choices=[('FEFO', 'FEFO — primero en vencer (perecederos, agroquímicos, carnes)'), ('FIFO', 'FIFO — primero en entrar (lote por antigüedad)'), ('AVERAGE', 'Promedio — fungible a granel (sin orden de lote)')], default='', help_text='FEFO/FIFO/AVERAGE; selección manual por producto (vacío = derivado)', max_length=16),
        ),
    ]
