# Generated by Django 5.2.12 on 2026-06-13 16:22

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0005_approvalrequest'),
        ('inventarios', '0009_inventoryitem_inventory_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='standard_cost',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), help_text='Costo estándar por unidad base (política de costeo STANDARD).', max_digits=18),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='cost_variance',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=18),
        ),
        migrations.CreateModel(
            name='StockMovementCostLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_cost', models.DecimalField(decimal_places=6, max_digits=18)),
                ('qty_initial', models.DecimalField(decimal_places=4, max_digits=18)),
                ('qty_remaining', models.DecimalField(decimal_places=4, max_digits=18)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inv_cost_layers_branch', to='iam.orgunit')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inv_cost_layers_company', to='iam.orgunit')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_layers', to='inventarios.inventoryitem')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_layers', to='inventarios.itemlot')),
                ('source_movement', models.ForeignKey(help_text='El movimiento de entrada (RECEIVE) que creó esta capa.', on_delete=django.db.models.deletion.PROTECT, related_name='cost_layers', to='inventarios.stockmovement')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_layers', to='inventarios.warehouse')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'branch', 'warehouse', 'item', 'created_at'], name='ix_costlayer_fifo')],
                'constraints': [models.CheckConstraint(condition=models.Q(('qty_remaining__gte', 0)), name='ck_costlayer_qty_remaining_gte_0'), models.CheckConstraint(condition=models.Q(('qty_initial__gt', 0)), name='ck_costlayer_qty_initial_gt_0')],
            },
        ),
    ]
