# Generated by Django 5.2.12 on 2026-03-24

from __future__ import annotations

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("iam", "0003_orgunit_parent_type_name_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardEmbedGrant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("jti", models.CharField(max_length=64, unique=True)),
                ("workspace_key", models.CharField(max_length=64)),
                ("perm_codes_json", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[("ISSUED", "Issued"), ("REDEEMED", "Redeemed"), ("EXPIRED", "Expired"), ("REVOKED", "Revoked")],
                        default="ISSUED",
                        max_length=16,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("redeemed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dashboard_embed_grants_branch",
                        to="iam.orgunit",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dashboard_embed_grants_company",
                        to="iam.orgunit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_embed_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="dashboardembedgrant",
            index=models.Index(fields=["status", "expires_at"], name="ix_dash_grant_status_exp"),
        ),
        migrations.AddIndex(
            model_name="dashboardembedgrant",
            index=models.Index(fields=["company", "branch", "created_at"], name="ix_dash_grant_scope"),
        ),
        migrations.AddIndex(
            model_name="dashboardembedgrant",
            index=models.Index(fields=["workspace_key", "created_at"], name="ix_dash_grant_workspace"),
        ),
    ]
