# Generated by Django 5.2.12 on 2026-06-12 17:33

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iam', '0005_approvalrequest'),
        ('inventarios', '0009_inventoryitem_inventory_class'),
        ('parties', '0001_initial'),
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeQualityGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=80)),
                ('default_tare_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tara sugerida por calidad (% del peso bruto; el SIFA: TaraCalidad).', max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financing_quality_grades', to='iam.orgunit')),
            ],
        ),
        migrations.CreateModel(
            name='CreditApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_nio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto solicitado en córdobas (puede ser 0 si solo pide dólares).', max_digits=18)),
                ('requested_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto solicitado en dólares (puede ser 0 si solo pide córdobas).', max_digits=18)),
                ('term_months', models.PositiveIntegerField(help_text='Plazo en meses.')),
                ('credit_type', models.CharField(blank=True, default='', help_text='Tipo de crédito (catálogo libre del SIFA: avío, comercial, etc.).', max_length=32)),
                ('activity', models.CharField(blank=True, default='', help_text='Actividad financiada (mantenimiento de café, recolección, etc.).', max_length=64)),
                ('interest_rate', models.DecimalField(decimal_places=4, help_text='Interés corriente anual (%).', max_digits=7)),
                ('penalty_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Interés moratorio anual (%).', max_digits=7)),
                ('commission_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Comisión sobre el monto desembolsado (%).', max_digits=7)),
                ('disbursement_form', models.CharField(choices=[('CASH', 'Efectivo'), ('CHECK', 'Cheque'), ('TRANSFER', 'Transferencia'), ('IN_KIND', 'Especie (insumos)')], default='CASH', max_length=16)),
                ('guarantee_farm_area_mz', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Garantía inmueble: área de finca (manzanas).', max_digits=12)),
                ('guarantee_solar', models.CharField(blank=True, default='', help_text='Garantía inmueble: solar.', max_length=255)),
                ('guarantee_other', models.CharField(blank=True, default='', help_text='Otras garantías.', max_length=255)),
                ('guarantee_coffee_qq', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Garantía mueble: café comprometido (quintales).', max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('SUBMITTED', 'Presentada'), ('APPROVED', 'Aprobada'), ('REJECTED', 'Rechazada'), ('DISBURSED', 'Desembolsada')], default='DRAFT', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financing_applications', to='iam.orgunit')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financing_applications_created', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financing_applications_decided', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_date', models.DateField()),
                ('rate', models.DecimalField(decimal_places=6, help_text='Córdobas por 1 dólar.', max_digits=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financing_exchange_rates', to='iam.orgunit')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financing_rates_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinancingLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='Número de préstamo (referencia del SIFA).', max_length=40)),
                ('credit_type', models.CharField(blank=True, default='', max_length=32)),
                ('activity', models.CharField(blank=True, default='', max_length=64)),
                ('interest_rate', models.DecimalField(decimal_places=4, max_digits=7)),
                ('penalty_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7)),
                ('commission_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7)),
                ('term_months', models.PositiveIntegerField()),
                ('maturity_date', models.DateField()),
                ('disbursement_form', models.CharField(choices=[('CASH', 'Efectivo'), ('CHECK', 'Cheque'), ('TRANSFER', 'Transferencia'), ('IN_KIND', 'Especie (insumos)')], default='CASH', max_length=16)),
                ('disbursed_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('PAID', 'Cancelado (pagado)'), ('CANCELLED', 'Anulado')], default='ACTIVE', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan', to='financiamiento.creditapplication')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financing_loans', to='iam.orgunit')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financing_loans_created', to=settings.AUTH_USER_MODEL)),
                ('credit_nio', models.OneToOneField(blank=True, help_text='Obligación del saldo en córdobas.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financing_loan_nio', to='portfolio.credit')),
                ('credit_usd', models.OneToOneField(blank=True, help_text='Obligación del saldo en dólares.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financing_loan_usd', to='portfolio.credit')),
            ],
        ),
        migrations.CreateModel(
            name='FinancingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coffee_item', models.ForeignKey(blank=True, help_text='Ítem de inventario que representa el café acopiado (UoM libra).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financing_settings', to='inventarios.inventoryitem')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='financing_settings', to='iam.orgunit')),
                ('custody_warehouse', models.ForeignKey(blank=True, help_text='Bodega de CUSTODIA (café del productor sin liquidar).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financing_custody_settings', to='inventarios.warehouse')),
                ('lender_party', models.ForeignKey(help_text='Party INTERNAL que representa a la empresa como acreedora.', on_delete=django.db.models.deletion.PROTECT, related_name='financing_lender_settings', to='parties.party')),
                ('liquidation_warehouse', models.ForeignKey(blank=True, help_text='Bodega propia a la que entra el café comprado al liquidar.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financing_own_settings', to='inventarios.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Liquidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liquidation_date', models.DateField()),
                ('currency', models.CharField(choices=[('NIO', 'Córdoba'), ('USD', 'Dólar')], max_length=8)),
                ('pounds_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('gross_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('deductions_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('applied_to_loan', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto abonado al préstamo (en la moneda de la obligación abonada).', max_digits=18)),
                ('applied_currency', models.CharField(blank=True, choices=[('NIO', 'Córdoba'), ('USD', 'Dólar')], default='', help_text='Moneda de la obligación abonada (puede diferir si cruzó con tasa).', max_length=8)),
                ('surplus_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Excedente a favor del productor (CxP).', max_digits=18)),
                ('exchange_rate_used', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('payment_intent_id', models.UUIDField(blank=True, null=True)),
                ('custody_issue_movement_id', models.PositiveIntegerField(blank=True, null=True)),
                ('own_receive_movement_id', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financing_liquidations', to='iam.orgunit')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financing_liquidations_created', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(blank=True, help_text='Préstamo abonado; NULL = liquidación sin deuda (todo excedente).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liquidations', to='financiamiento.financingloan')),
                ('payable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financing_liquidations', to='portfolio.payable')),
            ],
        ),
        migrations.CreateModel(
            name='LiquidationDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('liquidation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='financiamiento.liquidation')),
            ],
        ),
        migrations.CreateModel(
            name='ProducerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acopio_code', models.CharField(blank=True, default='', help_text='Código de acopio del productor (numeración histórica del SIFA).', max_length=32)),
                ('certifications', models.CharField(blank=True, default='', help_text='Certificaciones del productor (UTZ, orgánico, etc.).', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Empresa financiadora (acopiadora).', on_delete=django.db.models.deletion.PROTECT, related_name='financing_producers', to='iam.orgunit')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financing_producer_profiles', to='parties.party')),
            ],
        ),
        migrations.CreateModel(
            name='PriceFixation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixation_date', models.DateField()),
                ('pounds', models.DecimalField(decimal_places=2, help_text='Libras fijadas.', max_digits=14)),
                ('price_per_lb', models.DecimalField(decimal_places=4, help_text='Precio por libra (Valorflib del SIFA).', max_digits=12)),
                ('currency', models.CharField(choices=[('NIO', 'Córdoba'), ('USD', 'Dólar')], default='USD', max_length=8)),
                ('status', models.CharField(choices=[('OPEN', 'Fijada (sin liquidar)'), ('LIQUIDATED', 'Liquidada')], default='OPEN', max_length=16)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financing_fixations', to='iam.orgunit')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financing_fixations_created', to=settings.AUTH_USER_MODEL)),
                ('liquidation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixations', to='financiamiento.liquidation')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixations', to='financiamiento.producerprofile')),
            ],
        ),
        migrations.AddField(
            model_name='liquidation',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidations', to='financiamiento.producerprofile'),
        ),
        migrations.AddField(
            model_name='financingloan',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='financiamiento.producerprofile'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='financiamiento.producerprofile'),
        ),
        migrations.CreateModel(
            name='CoffeeReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reception_date', models.DateField()),
                ('reference', models.CharField(blank=True, default='', help_text='Número de recibo de café.', max_length=40)),
                ('physical_state', models.CharField(choices=[('MOJADO', 'Mojado'), ('HUMEDO', 'Húmedo'), ('OREADO', 'Oreado'), ('SECO', 'Pergamino seco')], default='HUMEDO', max_length=16)),
                ('sacks', models.PositiveIntegerField(help_text='Número de sacos.')),
                ('gross_lb', models.DecimalField(decimal_places=2, help_text='Libras brutas.', max_digits=14)),
                ('tare_lb', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tara en libras (por calidad/sacos).', max_digits=14)),
                ('net_lb', models.DecimalField(decimal_places=2, help_text='Libras netas.', max_digits=14)),
                ('stock_movement_id', models.PositiveIntegerField(blank=True, help_text='Movimiento RECEIVE en custodia (trazabilidad).', null=True)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financing_receptions', to='iam.orgunit')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financing_receptions_created', to=settings.AUTH_USER_MODEL)),
                ('quality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receptions', to='financiamiento.coffeequalitygrade')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financing_receptions', to='inventarios.warehouse')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receptions', to='financiamiento.producerprofile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='coffeequalitygrade',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uq_fin_quality_code'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['company', '-rate_date'], name='financiamie_company_710ab3_idx'),
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.UniqueConstraint(fields=('company', 'rate_date'), name='uq_fin_rate_date'),
        ),
        migrations.AddConstraint(
            model_name='producerprofile',
            constraint=models.UniqueConstraint(fields=('company', 'party'), name='uq_fin_producer_party'),
        ),
        migrations.AddConstraint(
            model_name='producerprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('acopio_code', ''), _negated=True), fields=('company', 'acopio_code'), name='uq_fin_producer_acopio_code'),
        ),
        migrations.AddIndex(
            model_name='pricefixation',
            index=models.Index(fields=['company', 'producer', 'status'], name='financiamie_company_9a0445_idx'),
        ),
        migrations.AddIndex(
            model_name='liquidation',
            index=models.Index(fields=['company', 'producer', 'liquidation_date'], name='financiamie_company_896ac3_idx'),
        ),
        migrations.AddIndex(
            model_name='financingloan',
            index=models.Index(fields=['company', 'status'], name='financiamie_company_be97c9_idx'),
        ),
        migrations.AddConstraint(
            model_name='financingloan',
            constraint=models.UniqueConstraint(fields=('company', 'reference'), name='uq_fin_loan_reference'),
        ),
        migrations.AddIndex(
            model_name='creditapplication',
            index=models.Index(fields=['company', 'status'], name='financiamie_company_8fafd9_idx'),
        ),
        migrations.AddIndex(
            model_name='coffeereception',
            index=models.Index(fields=['company', 'producer', 'reception_date'], name='financiamie_company_d3b8a7_idx'),
        ),
        migrations.AddConstraint(
            model_name='coffeereception',
            constraint=models.UniqueConstraint(condition=models.Q(('reference', ''), _negated=True), fields=('company', 'reference'), name='uq_fin_reception_reference'),
        ),
    ]
