# Generated by Django 5.2.9 on 2026-03-26 20:35

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estacion_servicios', '0010_rename_estacion_se_company__c8e61a_idx_estacion_se_company_54b2c6_idx_and_more'),
        ('iam', '0004_rename_iam_orgunit_parent_type_name_idx_iam_orgunit_parent__f0840d_idx'),
        ('payments', '0002_rename_payments_ca_session_80ee8d_idx_payments_ca_session_c5f759_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PosSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=16)),
                ('opening_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('counted_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('difference_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_sessions_branch', to='iam.orgunit')),
                ('cash_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retail_pos_sessions', to='payments.cashsession')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_sessions_closed', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_sessions_company', to='iam.orgunit')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_sessions_opened', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PosTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CART_OPEN', 'Cart open'), ('CHECKOUT_PENDING', 'Checkout pending'), ('PAID', 'Paid'), ('CLOSED', 'Closed'), ('VOIDED', 'Voided')], default='CART_OPEN', max_length=24)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=96)),
                ('correlation_id', models.CharField(blank=True, db_index=True, default='', max_length=96)),
                ('causation_id', models.CharField(blank=True, default='', max_length=96)),
                ('external_ref', models.CharField(blank=True, default='', max_length=96)),
                ('customer_name', models.CharField(blank=True, default='', max_length=200)),
                ('customer_ref', models.CharField(blank=True, default='', max_length=96)),
                ('sale_type', models.CharField(choices=[('INTERNAL', 'Consumo interno'), ('PUBLIC', 'Venta al público'), ('EMPLOYEE', 'Empleado (crédito/abonos)')], default='PUBLIC', max_length=16)),
                ('payment_method', models.CharField(choices=[('CASH', 'Efectivo'), ('TRANSFER', 'Transferencia'), ('CREDIT', 'Crédito')], default='CASH', max_length=16)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checkout_started_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, default='', max_length=255)),
                ('last_error', models.CharField(blank=True, default='', max_length=255)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_tickets_branch', to='iam.orgunit')),
                ('cash_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_tickets', to='payments.cashmovement')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_tickets_company', to='iam.orgunit')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_tickets_created', to=settings.AUTH_USER_MODEL)),
                ('payment_intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_tickets', to='payments.paymentintent')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_tickets', to='estacion_servicios.fuelsale')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='retail_pos.possession')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_tickets', to='estacion_servicios.fuelshift')),
            ],
        ),
        migrations.CreateModel(
            name='PosTicketLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField(default=1)),
                ('line_type', models.CharField(choices=[('FUEL', 'Fuel')], default='FUEL', max_length=16)),
                ('product', models.CharField(choices=[('DIESEL', 'Diesel'), ('GASOLINE', 'Gasolina')], max_length=16)),
                ('volume', models.DecimalField(decimal_places=4, max_digits=12)),
                ('volume_uom', models.CharField(choices=[('LITER', 'Litro'), ('GALLON', 'Galón (US)'), ('GALLON_US', 'Galón (US)')], default='LITER', max_length=16)),
                ('unit_price_entered', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unit_price_uom', models.CharField(choices=[('PER_LITER', 'Precio/Litro'), ('PER_GALLON', 'Precio/Galón (US)'), ('PER_GALLON_US', 'Precio/Galón (US)')], default='PER_LITER', max_length=16)),
                ('amount_estimated', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('metadata', models.JSONField(default=dict)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='retail_pos.posticket')),
            ],
        ),
        migrations.CreateModel(
            name='PosPeripheralStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector_id', models.CharField(max_length=96)),
                ('connector_version', models.CharField(blank=True, default='', max_length=32)),
                ('device_key', models.CharField(max_length=96)),
                ('device_kind', models.CharField(choices=[('THERMAL_PRINTER', 'Thermal printer'), ('SCANNER', 'Scanner'), ('DRAWER', 'Cash drawer'), ('SCALE', 'Scale'), ('PAYMENT_TERMINAL', 'Payment terminal')], max_length=32)),
                ('capability_level', models.CharField(choices=[('supported', 'Supported'), ('experimental', 'Experimental'), ('unsupported', 'Unsupported')], default='experimental', max_length=16)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('DEGRADED', 'Degraded')], default='ONLINE', max_length=16)),
                ('metadata', models.JSONField(default=dict)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_peripherals_branch', to='iam.orgunit')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_peripherals_company', to='iam.orgunit')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_peripherals_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'branch', 'status', 'last_seen_at'], name='retail_pos__company_51b39a_idx'), models.Index(fields=['device_kind', 'status'], name='retail_pos__device__16e19a_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'branch', 'device_key'), name='uq_pos_peripheral_company_branch_device')],
            },
        ),
        migrations.AddIndex(
            model_name='possession',
            index=models.Index(fields=['company', 'branch', 'status', 'opened_at'], name='retail_pos__company_405e37_idx'),
        ),
        migrations.AddConstraint(
            model_name='possession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('branch',), name='uq_open_pos_session_per_branch'),
        ),
        migrations.AddIndex(
            model_name='posticket',
            index=models.Index(fields=['company', 'branch', 'status', 'created_at'], name='retail_pos__company_ad0787_idx'),
        ),
        migrations.AddIndex(
            model_name='posticket',
            index=models.Index(fields=['status', 'updated_at'], name='retail_pos__status_89f153_idx'),
        ),
        migrations.AddConstraint(
            model_name='posticket',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('company', 'idempotency_key'), name='uq_pos_ticket_company_idempotency'),
        ),
        migrations.AddIndex(
            model_name='posticketline',
            index=models.Index(fields=['ticket', 'line_no'], name='retail_pos__ticket__69791c_idx'),
        ),
        migrations.AddIndex(
            model_name='posticketline',
            index=models.Index(fields=['product'], name='retail_pos__product_b8c67e_idx'),
        ),
        migrations.AddConstraint(
            model_name='posticketline',
            constraint=models.UniqueConstraint(fields=('ticket', 'line_no'), name='uq_pos_ticket_line_no'),
        ),
    ]
