# Generated by Django 5.2.9 on 2026-03-26 21:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0004_rename_iam_orgunit_parent_type_name_idx_iam_orgunit_parent__f0840d_idx'),
        ('retail_pos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PosEdgeChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('nonce', models.CharField(default='', max_length=96)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONSUMED', 'Consumed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=16)),
                ('connector_id', models.CharField(blank=True, default='', max_length=96)),
                ('connector_version', models.CharField(blank=True, default='', max_length=32)),
                ('metadata', models.JSONField(default=dict)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_edge_challenges_branch', to='iam.orgunit')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_edge_challenges_company', to='iam.orgunit')),
                ('consumed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_edge_challenges_consumed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_edge_challenges_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PosEdgeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=16)),
                ('connector_id', models.CharField(max_length=96)),
                ('connector_version', models.CharField(blank=True, default='', max_length=32)),
                ('capability_registry', models.JSONField(default=dict)),
                ('metadata', models.JSONField(default=dict)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_edge_sessions_branch', to='iam.orgunit')),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edge_sessions', to='retail_pos.posedgechallenge')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_edge_sessions_company', to='iam.orgunit')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_edge_sessions_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='posperipheralstatus',
            name='edge_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peripherals', to='retail_pos.posedgesession'),
        ),
        migrations.AddIndex(
            model_name='posedgechallenge',
            index=models.Index(fields=['company', 'branch', 'status', 'expires_at'], name='retail_pos__company_5a8ec1_idx'),
        ),
        migrations.AddIndex(
            model_name='posedgechallenge',
            index=models.Index(fields=['issued_at'], name='retail_pos__issued__37cd60_idx'),
        ),
        migrations.AddIndex(
            model_name='posedgesession',
            index=models.Index(fields=['company', 'branch', 'status', 'expires_at'], name='retail_pos__company_f36e82_idx'),
        ),
        migrations.AddIndex(
            model_name='posedgesession',
            index=models.Index(fields=['connector_id', 'status'], name='retail_pos__connect_3c577e_idx'),
        ),
        migrations.AddConstraint(
            model_name='posedgesession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('company', 'branch', 'connector_id'), name='uq_active_pos_edge_session_connector'),
        ),
    ]
