# Generated by Django 5.2.9 on 2026-03-26 21:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacion_servicios', '0010_rename_estacion_se_company__c8e61a_idx_estacion_se_company_54b2c6_idx_and_more'),
        ('iam', '0004_rename_iam_orgunit_parent_type_name_idx_iam_orgunit_parent__f0840d_idx'),
        ('payments', '0002_rename_payments_ca_session_80ee8d_idx_payments_ca_session_c5f759_idx_and_more'),
        ('retail_pos', '0002_posedgechallenge_posedgesession_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='posticket',
            name='compensation_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posticket',
            name='compensation_last_error',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='posticket',
            name='compensation_next_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posticket',
            name='compensation_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posticket',
            name='last_compensation_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='posticket',
            index=models.Index(fields=['status', 'compensation_pending', 'compensation_next_retry_at', 'updated_at'], name='retail_pos__status_0423b2_idx'),
        ),
    ]
