# Generated by Django 5.2.12 on 2026-03-26 22:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacion_servicios', '0010_rename_estacion_se_company__c8e61a_idx_estacion_se_company_54b2c6_idx_and_more'),
        ('iam', '0004_rename_iam_orgunit_parent_type_name_idx_iam_orgunit_parent__f0840d_idx'),
        ('payments', '0002_rename_payments_ca_session_80ee8d_idx_payments_ca_session_c5f759_idx_and_more'),
        ('retail_pos', '0003_posticket_compensation_attempts_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='posticket',
            constraint=models.CheckConstraint(condition=models.Q(('compensation_pending', False), models.Q(('status', 'CHECKOUT_PENDING'), ('compensation_attempts__gt', 0), ('compensation_next_retry_at__isnull', False)), _connector='OR'), name='ck_pos_ticket_comp_pending_state'),
        ),
        migrations.AddConstraint(
            model_name='posticket',
            constraint=models.CheckConstraint(condition=models.Q(('compensation_pending', True), ('status', 'CLOSED'), _negated=True), name='ck_pos_ticket_closed_no_comp_pending'),
        ),
        migrations.AddConstraint(
            model_name='posticket',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'CLOSED'), _negated=True), ('compensation_next_retry_at__isnull', True), _connector='OR'), name='ck_pos_ticket_closed_no_next_retry'),
        ),
    ]
