# Generated by Django 5.2.12 on 2026-04-10

from __future__ import annotations

from datetime import datetime, time

from django.db import migrations, models
from django.utils import timezone


BATCH_SIZE = 500


def _resolve_effective_at(*, created_at, source_entry_date):
    if source_entry_date is not None:
        candidate = datetime.combine(source_entry_date, time.min)
        if timezone.is_naive(candidate):
            return timezone.make_aware(candidate, timezone.get_current_timezone())
        return candidate
    return created_at or timezone.now()


def backfill_effective_at(apps, schema_editor):
    intercompany_tx_model = apps.get_model("accounting", "IntercompanyTransaction")
    journal_entry_model = apps.get_model("accounting", "JournalEntry")
    db_alias = schema_editor.connection.alias

    pending = []
    pending_source_ids: set[int] = set()
    queryset = intercompany_tx_model.objects.using(db_alias).all().only(
        "id",
        "created_at",
        "source_journal_entry_id",
        "effective_at",
    )

    def _flush_batch() -> None:
        if not pending:
            return
        source_entry_map: dict[int, object] = {}
        if pending_source_ids:
            for row in journal_entry_model.objects.using(db_alias).filter(id__in=sorted(pending_source_ids)).values(
                "id", "entry_date"
            ):
                source_entry_map[int(row["id"])] = row["entry_date"]

        for tx in pending:
            source_entry_date = source_entry_map.get(int(tx.source_journal_entry_id)) if tx.source_journal_entry_id else None
            tx.effective_at = _resolve_effective_at(
                created_at=tx.created_at,
                source_entry_date=source_entry_date,
            )
        intercompany_tx_model.objects.using(db_alias).bulk_update(pending, ["effective_at"], batch_size=BATCH_SIZE)
        pending.clear()
        pending_source_ids.clear()

    for tx in queryset.iterator(chunk_size=BATCH_SIZE):
        pending.append(tx)
        if tx.source_journal_entry_id:
            pending_source_ids.add(int(tx.source_journal_entry_id))
        if len(pending) >= BATCH_SIZE:
            _flush_batch()

    if pending:
        _flush_batch()


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0009_rename_acc_coa_comp_type_act_idx_accounting__company_41d161_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="intercompanytransaction",
            name="effective_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(backfill_effective_at, reverse_code=noop_reverse),
        migrations.AlterField(
            model_name="intercompanytransaction",
            name="effective_at",
            field=models.DateTimeField(db_index=True, default=timezone.now),
        ),
    ]
