# Generated by Django 5.2.12 on 2026-04-12

from __future__ import annotations

from django.db import migrations, models


SHADOW_PREFIX = "shadow_ledger_"


def mark_shadow_rule_family(apps, schema_editor):
    posting_ruleset_model = apps.get_model("accounting", "PostingRuleSet")
    db_alias = schema_editor.connection.alias
    posting_ruleset_model.objects.using(db_alias).filter(code__startswith=SHADOW_PREFIX).update(rule_family="SHADOW")


def revert_shadow_rule_family(apps, schema_editor):
    posting_ruleset_model = apps.get_model("accounting", "PostingRuleSet")
    db_alias = schema_editor.connection.alias
    posting_ruleset_model.objects.using(db_alias).filter(rule_family="SHADOW").update(rule_family="PRIMARY")


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0010_intercompany_effective_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="postingruleset",
            name="rule_family",
            field=models.CharField(
                choices=[("PRIMARY", "Primary"), ("SHADOW", "Shadow")], default="PRIMARY", max_length=16
            ),
        ),
        migrations.RunPython(mark_shadow_rule_family, reverse_code=revert_shadow_rule_family),
    ]
