# Generated by Django 5.2.12 on 2026-06-04 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_posting_ruleset_rule_family'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='journaldraft',
            name='generated_by',
            field=models.ForeignKey(blank=True, help_text='Actor humano que generó el draft (None si es proyección automática). SoD: no puede aprobarlo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acc_journal_drafts_generated', to=settings.AUTH_USER_MODEL),
        ),
    ]
