# Generated by Django 5.2.12 on 2026-06-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_journaldraft_generated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalpostingconfig',
            name='enable_nomina',
            field=models.BooleanField(default=True),
        ),
    ]
