# Generated by Django 5.2.12 on 2026-06-08 23:37

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iam', '0005_approvalrequest'),
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCreditAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(choices=[('EMPLOYEE', 'Trabajador de la hacienda'), ('PRODUCER', 'Productor'), ('PUBLIC', 'Público general')], max_length=16)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Límite de crédito; 0 = sin tope explícito.', max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collecting_company', models.ForeignKey(blank=True, help_text='Para EMPLOYEE: la finca/empresa que descuenta en planilla (cobra por cuenta del comisariato).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comisariato_collected_accounts', to='iam.orgunit')),
                ('company', models.ForeignKey(help_text='Empresa del comisariato (RUC propio) que otorga el crédito.', on_delete=django.db.models.deletion.PROTECT, related_name='comisariato_credit_accounts', to='iam.orgunit')),
                ('party', models.ForeignKey(help_text='Cliente (trabajador / productor / público).', on_delete=django.db.models.deletion.PROTECT, related_name='comisariato_credit_accounts', to='parties.party')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'is_active', 'segment'], name='ix_comis_acct_co_act_seg'), models.Index(fields=['party'], name='ix_comis_acct_party')],
                'constraints': [models.UniqueConstraint(fields=('company', 'party'), name='uq_comisariato_account_company_party'), models.CheckConstraint(condition=models.Q(('credit_limit__gte', 0)), name='ck_comisariato_account_limit_nonneg')],
            },
        ),
    ]
