# Generated by Django 5.2.12 on 2026-06-09 03:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisariato', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercreditaccount',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='NULL = sin tope (ilimitado, explícito); 0 = sin crédito; >0 = tope.', max_digits=18, null=True),
        ),
    ]
