# Generated by Django 5.2.12 on 2026-06-10 07:51

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('exception_type', models.CharField(max_length=255)),
                ('message_hash', models.CharField(blank=True, default='', max_length=64)),
                ('stack_hash', models.CharField(max_length=64, unique=True)),
                ('stack_trace_redacted', models.TextField(blank=True, default='')),
                ('file_path', models.CharField(blank=True, default='', max_length=512)),
                ('line_number', models.PositiveIntegerField(default=0)),
                ('function_name', models.CharField(blank=True, default='', max_length=255)),
                ('endpoint', models.CharField(blank=True, default='', max_length=512)),
                ('method', models.CharField(blank=True, default='', max_length=16)),
                ('http_status', models.PositiveSmallIntegerField(default=500)),
                ('domain', models.CharField(blank=True, default='', max_length=64)),
                ('risk_class', models.CharField(choices=[('C1', 'C1 — dinero/stock/fiscal/permisos/CEC/auditoría'), ('C2', 'C2 — confiabilidad/trazabilidad/API/reporting'), ('C3', 'C3 — deuda/estilo/baja exposición')], default='C3', max_length=2)),
                ('correlation_id', models.CharField(blank=True, default='', max_length=64)),
                ('company_id', models.CharField(blank=True, default='', max_length=64)),
                ('branch_id', models.CharField(blank=True, default='', max_length=64)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('triaged', 'Triado'), ('confirmed', 'Confirmado'), ('fixed', 'Corregido'), ('regressed', 'Regresado'), ('accepted_risk', 'Riesgo aceptado'), ('false_positive', 'Falso positivo')], default='open', max_length=16)),
                ('owner', models.CharField(blank=True, default='', max_length=128)),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['stack_hash'], name='diagnostics_stack_h_e404cd_idx'), models.Index(fields=['domain', 'risk_class'], name='diagnostics_domain_b434cd_idx'), models.Index(fields=['status', '-last_seen_at'], name='diagnostics_status_606173_idx')],
            },
        ),
    ]
