# Generated by Django 5.2.12 on 2026-06-10 13:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_enabled', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_control_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_tool', models.CharField(max_length=32)),
                ('vuln_id', models.CharField(max_length=128)),
                ('package', models.CharField(blank=True, default='', max_length=255)),
                ('package_version', models.CharField(blank=True, default='', max_length=64)),
                ('fixed_version', models.CharField(blank=True, default='', max_length=64)),
                ('cve_id', models.CharField(blank=True, default='', max_length=64)),
                ('cwe_id', models.CharField(blank=True, default='', max_length=32)),
                ('file_path', models.CharField(blank=True, default='', max_length=512)),
                ('line_start', models.PositiveIntegerField(default=0)),
                ('symbol', models.CharField(blank=True, default='', max_length=255)),
                ('domain', models.CharField(blank=True, default='', max_length=64)),
                ('severity_raw', models.CharField(blank=True, default='', max_length=32)),
                ('risk_class', models.CharField(choices=[('C1', 'C1 — dinero/stock/fiscal/permisos/CEC/auditoría'), ('C2', 'C2 — confiabilidad/trazabilidad/API/reporting'), ('C3', 'C3 — deuda/estilo/baja exposición')], default='C3', max_length=2)),
                ('reachable', models.CharField(default='unknown', max_length=8)),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('triaged', 'Triado'), ('confirmed', 'Confirmado'), ('fixed', 'Corregido (ya no aparece)'), ('accepted_risk', 'Riesgo aceptado (excepción vigente)'), ('false_positive', 'Falso positivo')], default='open', max_length=16)),
                ('owner', models.CharField(blank=True, default='', max_length=128)),
                ('accepted_risk_reason', models.CharField(blank=True, default='', max_length=255)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['source_tool', 'status'], name='diagnostics_source__2f41df_idx'), models.Index(fields=['risk_class', 'status'], name='diagnostics_risk_cl_ded2d0_idx'), models.Index(fields=['status', '-last_seen_at'], name='diagnostics_status_c23d73_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_tool', 'package', 'vuln_id'), name='uniq_securityfinding_natural_key')],
            },
        ),
    ]
