# Generated by Django 5.2.12 on 2026-06-10 13:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0002_aicontrol_securityfinding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('subject_type', models.CharField(default='error_event', max_length=32)),
                ('subject_id', models.CharField(max_length=64)),
                ('trigger_type', models.CharField(default='manual', max_length=16)),
                ('domain', models.CharField(blank=True, default='', max_length=64)),
                ('risk_class', models.CharField(choices=[('C1', 'C1 — dinero/stock/fiscal/permisos/CEC/auditoría'), ('C2', 'C2 — confiabilidad/trazabilidad/API/reporting'), ('C3', 'C3 — deuda/estilo/baja exposición')], default='C3', max_length=2)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('summary', models.TextField(blank=True, default='')),
                ('blast_radius', models.JSONField(blank=True, default=dict)),
                ('root_cause_hypothesis', models.TextField(blank=True, default='')),
                ('recommended_tests', models.TextField(blank=True, default='')),
                ('recommended_fix', models.TextField(blank=True, default='')),
                ('confidence', models.CharField(blank=True, default='', max_length=8)),
                ('ai_assisted', models.BooleanField(default=False)),
                ('generated_by', models.CharField(default='deterministic', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('reviewed', 'Revisado'), ('accepted', 'Aceptado'), ('dismissed', 'Descartado')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_runs', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subject_type', 'subject_id'], name='diagnostics_subject_5909e3_idx'), models.Index(fields=['risk_class', '-created_at'], name='diagnostics_risk_cl_c2a6b6_idx'), models.Index(fields=['status', '-created_at'], name='diagnostics_status_97dc9f_idx')],
            },
        ),
    ]
