# Generated by Django 5.2.12 on 2026-06-10 15:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0003_diagnosticrun'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('agent_name', models.CharField(max_length=64)),
                ('model_id', models.CharField(blank=True, default='', max_length=64)),
                ('prompt_version', models.CharField(blank=True, default='', max_length=32)),
                ('status', models.CharField(default='completed', max_length=16)),
                ('confidence', models.CharField(blank=True, default='', max_length=8)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('cost_estimate', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_agent_runs', to=settings.AUTH_USER_MODEL)),
                ('subject_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runs', to='diagnostics.diagnosticrun')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent_name', '-created_at'], name='diagnostics_agent_n_a7b91e_idx')],
            },
        ),
    ]
