# Generated by Django 5.2.12 on 2026-06-10 15:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0004_aiagentrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeUnitEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=512)),
                ('line_start', models.PositiveIntegerField()),
                ('line_end', models.PositiveIntegerField(default=0)),
                ('symbol', models.CharField(blank=True, default='', max_length=255)),
                ('domain', models.CharField(blank=True, default='', max_length=64)),
                ('coverage_state', models.CharField(choices=[('covered', 'Cubierta por tests'), ('uncovered', 'Sin cobertura'), ('unknown', 'Desconocida (no medida)')], default='unknown', max_length=16)),
                ('error_refs', models.JSONField(blank=True, default=list)),
                ('security_refs', models.JSONField(blank=True, default=list)),
                ('last_commit', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['domain', 'coverage_state'], name='diagnostics_domain_87f957_idx'), models.Index(fields=['coverage_state'], name='diagnostics_coverag_97f382_idx')],
                'constraints': [models.UniqueConstraint(fields=('path', 'line_start'), name='uniq_codeunit_path_line')],
            },
        ),
    ]
