# Generated by Django 5.2.12 on 2026-03-25 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cashmovement',
            new_name='payments_ca_session_c5f759_idx',
            old_name='payments_ca_session_80ee8d_idx',
        ),
        migrations.RenameIndex(
            model_name='cashsession',
            new_name='payments_ca_company_6cd6df_idx',
            old_name='payments_ca_company_5f25f0_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentintent',
            new_name='payments_pa_company_500e91_idx',
            old_name='payments_pa_company_745d5f_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentintent',
            new_name='payments_pa_provide_9e84a3_idx',
            old_name='payments_pa_provider_83867f_idx',
        ),
    ]
