# Generated by Codex on 2026-05-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_rename_payments_ca_session_80ee8d_idx_payments_ca_session_c5f759_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashmovement",
            name="idempotency_key",
            field=models.CharField(blank=True, default="", max_length=96),
        ),
        migrations.AddIndex(
            model_name="cashmovement",
            index=models.Index(fields=["session", "idempotency_key"], name="ix_cashmov_session_idem"),
        ),
        migrations.AddConstraint(
            model_name="cashmovement",
            constraint=models.UniqueConstraint(
                condition=~models.Q(idempotency_key=""),
                fields=["session", "idempotency_key"],
                name="uq_cash_movement_session_idempotency",
            ),
        ),
    ]
