# Generated by Django 5.2.12 on 2026-05-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_cashmovement_idempotency'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentintent',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('', 'Unknown / historical'), ('CASH', 'Cash'), ('TRANSFER', 'Transfer'), ('CREDIT', 'Credit'), ('CARD', 'Card')], default='', max_length=16),
        ),
    ]
