# Generated by Django 5.2.9 on 2026-06-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymentintent_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentintent',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('', 'Sin especificar'), ('CASH', 'Efectivo'), ('TRANSFER', 'Transferencia Bancaria'), ('CREDIT', 'Crédito'), ('CARD', 'Tarjeta'), ('CHECK', 'Cheque'), ('PAYROLL_DEDUCTION', 'Descuento de Nómina'), ('PRODUCER_CREDIT', 'Crédito Productor (Café)'), ('INTERNAL_TRANSFER', 'Traslado Interno'), ('COFFEE_QUOTA', 'Cuota de Café (especie)'), ('MIXED', 'Mixto')], default='', max_length=24),
        ),
    ]
