# Generated by Django 5.2.9 on 2026-06-02 22:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0004_rename_iam_orgunit_parent_type_name_idx_iam_orgunit_parent__f0840d_idx'),
        ('payments', '0005_alter_paymentintent_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashDenomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination_type', models.CharField(choices=[('BILL', 'Billete'), ('COIN', 'Moneda')], max_length=8)),
                ('denomination_value', models.DecimalField(decimal_places=2, help_text='Valor de la denominación (ej: 100.00 para billete de C$100)', max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='denomination_value * quantity — calculado automáticamente', max_digits=18)),
            ],
            options={
                'ordering': ['-denomination_type', '-denomination_value'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='NIO', max_length=8)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=96)),
                ('provider_refund_id', models.CharField(blank=True, default='', max_length=96)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='payment_intent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements', to='payments.paymentintent'),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('', 'Sin especificar'), ('CASH', 'Efectivo'), ('TRANSFER', 'Transferencia Bancaria'), ('CREDIT', 'Crédito'), ('CARD', 'Tarjeta'), ('CHECK', 'Cheque'), ('PAYROLL_DEDUCTION', 'Descuento de Nómina'), ('PRODUCER_CREDIT', 'Crédito Productor (Café)'), ('INTERNAL_TRANSFER', 'Traslado Interno'), ('COFFEE_QUOTA', 'Cuota de Café (especie)'), ('MIXED', 'Mixto')], default='', help_text='Método de pago de este movimiento específico', max_length=24),
        ),
        migrations.AddField(
            model_name='cashsession',
            name='register_id',
            field=models.CharField(blank=True, default='', help_text='Identificador del punto de venta (ej: CAJA-1, POS-COMISARIATO-A)', max_length=64),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='amount_authorized',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto autorizado (puede ser parcial)', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='amount_captured',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto capturado/cobrado efectivamente', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='amount_refunded',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total reembolsado (acumulado)', max_digits=18),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='cancellation_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='movement_type',
            field=models.CharField(choices=[('INCOME', 'Ingreso'), ('EXPENSE', 'Egreso'), ('ADJUSTMENT', 'Ajuste'), ('REFUND', 'Devolución')], db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='cashsession',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('COUNT_PENDING', 'Count pending'), ('REVIEW_PENDING', 'Review pending'), ('CLOSED', 'Closed'), ('REOPENED_FOR_INVESTIGATION', 'Reopened for investigation')], db_index=True, default='OPEN', max_length=32),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='status',
            field=models.CharField(choices=[('INTENDED', 'Intended'), ('AUTHORIZED', 'Authorized'), ('CAPTURED', 'Captured'), ('PARTIALLY_CAPTURED', 'Partially Captured'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially Refunded'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='INTENDED', max_length=24),
        ),
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['session', 'movement_type'], name='payments_ca_session_b1fd87_idx'),
        ),
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['payment_intent'], name='ix_cashmov_intent'),
        ),
        migrations.AddIndex(
            model_name='cashsession',
            index=models.Index(fields=['company', 'branch', 'register_id', 'status'], name='payments_ca_company_9ee8ca_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['company', 'payment_method', 'status'], name='payments_pa_company_4d9596_idx'),
        ),
        migrations.AddConstraint(
            model_name='cashsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('branch', 'register_id'), name='uq_cash_session_open_per_register'),
        ),
        migrations.AddField(
            model_name='cashdenomination',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denominations', to='payments.cashsession'),
        ),
        migrations.AddField(
            model_name='paymentrefund',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pay_refunds_company', to='iam.orgunit'),
        ),
        migrations.AddField(
            model_name='paymentrefund',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pay_refunds_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentrefund',
            name='intent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.paymentintent'),
        ),
        migrations.AddConstraint(
            model_name='cashdenomination',
            constraint=models.UniqueConstraint(fields=('session', 'denomination_value'), name='uq_cash_denom_session_value'),
        ),
        migrations.AddIndex(
            model_name='paymentrefund',
            index=models.Index(fields=['intent', 'created_at'], name='payments_pa_intent__e571f1_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrefund',
            index=models.Index(fields=['company', 'created_at'], name='payments_pa_company_5ca627_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentrefund',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_pay_refund_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentrefund',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('intent', 'idempotency_key'), name='uq_pay_refund_intent_idempotency'),
        ),
    ]
