# Generated by Django 5.2.12 on 2026-03-25 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cec', '0002_phase3_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cecexception',
            new_name='cec_cecexce_status_20932b_idx',
            old_name='cec_cecexc_status_826f17_idx',
        ),
        migrations.RenameIndex(
            model_name='cecexception',
            new_name='cec_cecexce_company_7760bc_idx',
            old_name='cec_cecexc_company_e8f12c_idx',
        ),
        migrations.RenameIndex(
            model_name='closerun',
            new_name='cec_closeru_company_9cfa68_idx',
            old_name='cec_closeru_company_d4469f_idx',
        ),
        migrations.RenameIndex(
            model_name='closerun',
            new_name='cec_closeru_company_d1259b_idx',
            old_name='cec_closeru_company_2a5de2_idx',
        ),
        migrations.RenameIndex(
            model_name='evidenceartifact',
            new_name='cec_evidenc_close_r_918d6b_idx',
            old_name='cec_evidenc_close_r_b93cf2_idx',
        ),
    ]
