# Generated by Django 5.2.12 on 2026-06-03 17:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iam', '0004_rename_iam_orgunit_parent_type_name_idx_iam_orgunit_parent__f0840d_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=128)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('platform', models.CharField(choices=[('WEB', 'Web'), ('ANDROID', 'Android'), ('IOS', 'iOS'), ('POS', 'Punto de venta'), ('EDGE', 'Edge/Conector'), ('UNKNOWN', 'Desconocido')], default='UNKNOWN', max_length=16)),
                ('trusted', models.BooleanField(default=False)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='known_devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('company_id', models.BigIntegerField(blank=True, null=True)),
                ('branch_id', models.BigIntegerField(blank=True, null=True)),
                ('refresh_jti', models.CharField(blank=True, default='', max_length=64)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, choices=[('LOGOUT', 'Logout'), ('EXPIRED', 'Expirada'), ('REVOKED', 'Revocada'), ('REPLACED', 'Reemplazada')], default='', max_length=16)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='activity.deviceregistry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.BigIntegerField(blank=True, null=True)),
                ('branch_id', models.BigIntegerField(blank=True, null=True)),
                ('route', models.CharField(blank=True, default='', max_length=255)),
                ('method', models.CharField(blank=True, default='', max_length=16)),
                ('status_code', models.PositiveSmallIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_events', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='activity.deviceregistry')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='activity.usersession')),
            ],
        ),
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('WEB', 'Web'), ('POS', 'Punto de venta'), ('KIOSK', 'Kiosco'), ('MANUAL', 'Manual')], default='WEB', max_length=16)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('clock_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_sessions_branch', to='iam.orgunit')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_sessions_company', to='iam.orgunit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='deviceregistry',
            index=models.Index(fields=['user', 'revoked_at'], name='activity_de_user_id_e2a7e0_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceregistry',
            index=models.Index(fields=['last_seen_at'], name='activity_de_last_se_e58bf6_idx'),
        ),
        migrations.AddConstraint(
            model_name='deviceregistry',
            constraint=models.UniqueConstraint(fields=('user', 'fingerprint'), name='uq_device_user_fingerprint'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'ended_at'], name='activity_us_user_id_b7fca9_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['started_at'], name='activity_us_started_9a14a7_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['refresh_jti'], name='activity_us_refresh_5d36ac_idx'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['user', 'occurred_at'], name='activity_ac_user_id_92080e_idx'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['company_id', 'occurred_at'], name='activity_ac_company_61e6fe_idx'),
        ),
        migrations.AddIndex(
            model_name='worksession',
            index=models.Index(fields=['user', 'clock_out'], name='activity_wo_user_id_bd304f_idx'),
        ),
        migrations.AddIndex(
            model_name='worksession',
            index=models.Index(fields=['company', 'branch', 'clock_in'], name='activity_wo_company_6c48ba_idx'),
        ),
        migrations.AddConstraint(
            model_name='worksession',
            constraint=models.UniqueConstraint(condition=models.Q(('clock_out__isnull', True)), fields=('user', 'company'), name='uq_open_work_session_user_company'),
        ),
    ]
