from django.urls import path

from .views import (
    ContractAnnulView,
    ContractDetailView,
    ContractIssueView,
    EmployeeAssignmentListCreateView,
    EmployeeAssignmentEndView,
    EmployeeContractListCreateView,
    EmployeeDetailView,
    EmployeeLifecycleListView,
    EmployeeListCreateView,
    EmployeeMemoListCreateView,
    EmployeePhotoView,
    EmployeeProfileView,
    EmployeeProvisionUserView,
    EmployeeRehireView,
    EmployeeReinstateView,
    EmployeeRevokeAccessView,
    EmployeeResetTempPasswordView,
    EmployeeRoleMapView,
    EmployeeSuspendView,
    EmployeeTerminateView,
    HrCatalogsView,
    MemoAnnulView,
    OnboardingSummaryView,
    PositionDetailView,
    PositionListCreateView,
    PositionRoleMapUpdateView,
)

urlpatterns = [
    path("onboarding/summary/", OnboardingSummaryView.as_view()),
    path("catalogs/", HrCatalogsView.as_view()),
    path("positions/", PositionListCreateView.as_view()),
    path("positions/<int:position_id>/", PositionDetailView.as_view()),
    path("positions/<int:position_id>/roles/", PositionRoleMapUpdateView.as_view()),
    path("employees/", EmployeeListCreateView.as_view()),
    path("employees/<int:employee_id>/", EmployeeDetailView.as_view()),
    path("employees/<int:employee_id>/profile/", EmployeeProfileView.as_view()),
    path("employees/<int:employee_id>/photo/", EmployeePhotoView.as_view()),
    path("employees/<int:employee_id>/roles/", EmployeeRoleMapView.as_view()),
    path("employees/<int:employee_id>/assignments/", EmployeeAssignmentListCreateView.as_view()),
    path("employees/<int:employee_id>/assignments/<int:assignment_id>/end/", EmployeeAssignmentEndView.as_view()),
    path("employees/<int:employee_id>/provision-user/", EmployeeProvisionUserView.as_view()),
    path("employees/<int:employee_id>/reset-temp-password/", EmployeeResetTempPasswordView.as_view()),
    path("employees/<int:employee_id>/revoke-access/", EmployeeRevokeAccessView.as_view()),
    # Ciclo de vida laboral
    path("employees/<int:employee_id>/lifecycle/", EmployeeLifecycleListView.as_view()),
    path("employees/<int:employee_id>/suspend/", EmployeeSuspendView.as_view()),
    path("employees/<int:employee_id>/reinstate/", EmployeeReinstateView.as_view()),
    path("employees/<int:employee_id>/terminate/", EmployeeTerminateView.as_view()),
    path("employees/<int:employee_id>/rehire/", EmployeeRehireView.as_view()),
    # Contratos laborales
    path("employees/<int:employee_id>/contracts/", EmployeeContractListCreateView.as_view()),
    path("contracts/<int:contract_id>/", ContractDetailView.as_view()),
    path("contracts/<int:contract_id>/issue/", ContractIssueView.as_view()),
    path("contracts/<int:contract_id>/annul/", ContractAnnulView.as_view()),
    # Memorandos
    path("employees/<int:employee_id>/memos/", EmployeeMemoListCreateView.as_view()),
    path("memos/<int:memo_id>/annul/", MemoAnnulView.as_view()),
]
