# Generated by Django 5.2.5 on 2026-03-24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("iam", "0003_orgunit_parent_type_name_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportDatasetDefinition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("dataset_key", models.CharField(max_length=128, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("domain_owner", models.CharField(max_length=64)),
                (
                    "scope_level",
                    models.CharField(
                        choices=[("COMPANY", "Company"), ("BRANCH", "Branch")],
                        default="COMPANY",
                        max_length=16,
                    ),
                ),
                ("required_permissions_json", models.JSONField(default=list)),
                ("filters_schema_json", models.JSONField(default=dict)),
                ("dimensions_schema_json", models.JSONField(default=list)),
                ("measures_schema_json", models.JSONField(default=list)),
                (
                    "freshness_mode",
                    models.CharField(
                        choices=[
                            ("LIVE_ONLY", "Live only"),
                            ("CACHE_ALLOWED", "Cache allowed"),
                            ("SNAPSHOT_REQUIRED", "Snapshot required"),
                        ],
                        default="LIVE_ONLY",
                        max_length=32,
                    ),
                ),
                (
                    "materialization_policy",
                    models.CharField(
                        choices=[
                            ("LIVE_ONLY", "Live only"),
                            ("CACHE_ALLOWED", "Cache allowed"),
                            ("SNAPSHOT_REQUIRED", "Snapshot required"),
                        ],
                        default="LIVE_ONLY",
                        max_length=32,
                    ),
                ),
                ("export_capabilities_json", models.JSONField(default=list)),
                ("render_hints_json", models.JSONField(default=dict)),
                ("schema_version", models.CharField(default="1.0.0", max_length=16)),
                ("semantic_version", models.CharField(default="1.0.0", max_length=16)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("CERTIFIED", "Certified"),
                            ("DEPRECATED", "Deprecated"),
                            ("RETIRED", "Retired"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("is_certified", models.BooleanField(default=False)),
                ("is_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["domain_owner", "is_enabled"], name="ix_rep_ds_owner_enabled"),
                    models.Index(fields=["status", "is_enabled"], name="ix_rep_ds_status_enabled"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ReportRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("run_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("dataset_key", models.CharField(db_index=True, max_length=128)),
                ("filters_json", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[("RUNNING", "Running"), ("SUCCEEDED", "Succeeded"), ("FAILED", "Failed")],
                        default="RUNNING",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("result_hash", models.CharField(blank=True, default="", max_length=64)),
                ("warnings_json", models.JSONField(default=list)),
                ("source_summary_json", models.JSONField(default=dict)),
                ("lineage_json", models.JSONField(default=dict)),
                (
                    "consumer_type",
                    models.CharField(
                        choices=[("API", "API"), ("DASHBOARD", "Dashboard"), ("JOB", "Job"), ("EXPORT", "Export")],
                        default="API",
                        max_length=16,
                    ),
                ),
                ("consumer_ref", models.CharField(blank=True, default="", max_length=128)),
                ("schema_version_used", models.CharField(default="1.0.0", max_length=16)),
                ("semantic_version_used", models.CharField(default="1.0.0", max_length=16)),
                ("error_detail", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reporting_runs_branch",
                        to="iam.orgunit",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reporting_runs_company",
                        to="iam.orgunit",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reporting_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["dataset_key", "created_at"], name="ix_rep_run_ds_created"),
                    models.Index(fields=["status", "created_at"], name="ix_rep_run_status_created"),
                    models.Index(fields=["company", "branch", "created_at"], name="ix_rep_run_scope_created"),
                ],
            },
        ),
    ]

