# Generated by Django 5.2.12 on 2026-06-11 14:56

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_path', models.CharField(max_length=512)),
                ('heading', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('content', models.TextField()),
                ('file_checksum', models.CharField(max_length=64)),
                ('search', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('ingested_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['source_path', 'order'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search'], name='gin_knowledgechunk_search'), models.Index(fields=['source_path'], name='knowledge_k_source__dbb085_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_path', 'order'), name='uniq_knowledgechunk_path_order')],
            },
        ),
    ]
