# Generated by Django 5.2.12 on 2026-03-25 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_two_factor_challenge'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='refreshtokensession',
            new_name='accounts_re_user_id_7e85a1_idx',
            old_name='accounts_re_user_id_6cc004_idx',
        ),
        migrations.RenameIndex(
            model_name='refreshtokensession',
            new_name='accounts_re_expires_ad9c6a_idx',
            old_name='accounts_re_expires_83b3b2_idx',
        ),
        migrations.RenameIndex(
            model_name='twofactorchallenge',
            new_name='accounts_tw_user_id_134482_idx',
            old_name='accounts_two_user_expires_idx',
        ),
        migrations.RenameIndex(
            model_name='twofactorchallenge',
            new_name='accounts_tw_used_at_096844_idx',
            old_name='accounts_two_used_idx',
        ),
    ]
