from __future__ import annotations

ALLOWED_EVENT_TYPES: set[str] = {
    # AUTH
    "AUTH_LOGIN_SUCCESS",
    "AUTH_LOGIN_FAILURE",
    "AUTH_BOOTSTRAP_ADMIN_CREATED",
    "IAM_BOOTSTRAP_ORG_CREATED",
    "AUTH_PASSWORD_CHANGED",
    "AUTH_PASSWORD_CHANGE_FAILURE",
    "AUTH_TOKEN_REFRESH",
    "AUTH_TOKEN_REFRESH_FAILURE",
    "AUTH_LOGOUT",
    "AUTH_LOGOUT_FAILURE",
    "AUTH_LOCKOUT_TRIGGERED",
    "AUTH_ACCESS_DENIED",
    "AUTH_2FA_SETUP_STARTED",
    "AUTH_2FA_ENABLED",
    "AUTH_2FA_DISABLED",
    "AUTH_2FA_CHALLENGE",
    "AUTH_2FA_VERIFIED",
    "AUTH_2FA_FAILED",
    # SYNC
    "SYNC_ENROLL_CHALLENGE_CREATED",
    "SYNC_DEVICE_ENROLLED",
    "SYNC_DEVICE_REVOKED",
    "SYNC_BATCH_RECEIVED",
    "SYNC_COMMAND_APPLIED",
    "SYNC_COMMAND_REJECTED",
    "SYNC_COMMAND_DUPLICATE",
    "SYNC_AUTH_REJECTED",
    # RBAC
    "RBAC_SEEDED_V01",
    # ORG
    "ORG_BRANCH_CREATED",
    "ORG_BRANCH_UPDATED",
    "ORG_COMPANY_CREATED",
    "ORG_COMPANY_PROFILE_UPDATED",
    "ORG_MODULES_UPDATED",
    # HR
    "HR_POSITION_CREATED",
    "HR_POSITION_UPDATED",
    "HR_POSITION_ROLEMAP_UPDATED",
    "HR_EMPLOYEE_ROLEMAP_UPDATED",
    "HR_EMPLOYEE_CREATED",
    "HR_EMPLOYEE_UPDATED",
    "HR_EMPLOYEE_PARTY_LINK_CHANGED",
    "HR_EMPLOYEE_PHOTO_SET",
    "HR_EMPLOYEE_PHOTO_REMOVED",
    "HR_EMPLOYEE_USER_PROVISIONED",
    "HR_EMPLOYEE_TEMP_PASSWORD_RESET",
    "HR_EMPLOYEE_ACCESS_REVOKED",
    "HR_ASSIGNMENT_CREATED",
    "HR_ASSIGNMENT_ENDED",
    "HR_RECONCILE_APPLIED",
    "HR_EMPLOYEE_SUSPENDED",
    "HR_EMPLOYEE_REINSTATED",
    "HR_EMPLOYEE_TERMINATED",
    "HR_EMPLOYEE_REHIRED",
    "HR_CONTRACT_CREATED",
    "HR_CONTRACT_UPDATED",
    "HR_CONTRACT_ISSUED",
    "HR_CONTRACT_ANNULLED",
    "HR_MEMO_CREATED",
    "HR_MEMO_ANNULLED",

    # FUEL (Estación de Servicios)
    "FUEL_SHIFT_OPENED",
    "FUEL_SHIFT_CLOSED",
    "FUEL_PRICE_SET",
    "FUEL_DISPENSE_RECORDED",
    "FUEL_DISPENSE_VOIDED",
    "FUEL_SALE_CREATED",
    "FUEL_SALE_VOIDED",
    "FUEL_TANK_RECEIPT_POSTED",
    "FUEL_TANK_ADJUSTMENT_POSTED",
    "FUEL_RECONCILIATION_POSTED",
    "FUEL_INTERCOMPANY_OUTBOX_ENQUEUED",
    "FUEL_INTERCOMPANY_OUTBOX_APPLIED",
    "FUEL_INTERCOMPANY_OUTBOX_FAILED",

    # INVENTORY
    "INVENTORY_ITEM_CREATED",
    "INVENTORY_ITEM_UPDATED",
    "INVENTORY_WAREHOUSE_CREATED",
    # NOMINA
    "NOMINA_CONFIG_CREATED",
    "NOMINA_CONFIG_UPDATED",
    "NOMINA_IR_TABLE_UPDATED",
    "NOMINA_PERIOD_CREATED",
    "NOMINA_SHEET_CREATED",
    "NOMINA_SHEET_SUBMITTED",
    "NOMINA_SHEET_APPROVED",
    "NOMINA_EMPLOYEE_INSS_REGIME_CHANGED",
    "NOMINA_INSS_ELECTION_SET",
    "NOMINA_ENTRIES_RECLASSIFIED",
    "NOMINA_PERIOD_APPROVED",
    "NOMINA_PAYROLL_POSTED",
    "NOMINA_PAYMENT_REGISTERED",
    "NOMINA_PERIOD_PAID",
    "NOMINA_PERIOD_CLOSED",
    "NOMINA_LOAN_DEDUCTION_RECORDED",
    "NOMINA_ASISTENCIA_MARCADA",
    "NOMINA_BIOMETRIC_DEVICE_CREATED",
    "NOMINA_BIOMETRIC_DEVICE_UPDATED",
    "NOMINA_BIOMETRIC_IMPORTED",
    "NOMINA_BIOMETRIC_MAP_SET",
    "NOMINA_BIOMETRIC_ROLLUP_APPLIED",
    "FIELD_CREW_CREATED",
    "FIELD_WORK_DAY_UPSERTED",
    "FIELD_CREW_REPORT_SUBMITTED",
    "FIELD_WORKER_EVENT_RECORDED",
    "FIELD_WORKER_TRANSFER_RECORDED",
    "FIELD_CREW_REPORT_APPROVED",
    "ATTENDANCE_REPORT_BUILT",
    "INVENTORY_WAREHOUSE_UPDATED",
    "INVENTORY_LOT_CREATED",
    "INVENTORY_LOT_UPDATED",

    # BILLING
    "BILLING_CUSTOMER_CREATED",
    "BILLING_CUSTOMER_UPDATED",
    "BILLING_INVOICE_CREATED",
    "BILLING_INVOICE_ISSUED",
    "BILLING_INVOICE_VOIDED",
    "BILLING_PAYMENT_ADDED",
    "BILLING_PAYMENT_REVERSED",
    "BILLING_ORDER_CREATED",
    "BILLING_ORDER_SUBMITTED",
    "BILLING_CREDIT_REQUESTED",
    "BILLING_CREDIT_APPROVED",
    "BILLING_CREDIT_REJECTED",
    "BILLING_CREDIT_ESCALATED",
    # RETAIL POS
    "POS_SESSION_OPENED",
    "POS_SESSION_CLOSED",
    "POS_TICKET_CLOSED",
    "POS_TICKET_VOIDED",
    # PAYMENTS
    "PAYMENTS_CASH_MOVEMENT_POSTED",
}

# Event Types (añadir)
ALLOWED_EVENT_TYPES.update(
    {
        "INVENTORY_MOVEMENT_POSTED",
        "INVENTORY_ADJUSTMENT_POSTED",
        "INVENTORY_TRANSFER_POSTED",
        "BILLING_DOC_CREATED",
        "BILLING_DOC_ISSUED",
        "BILLING_DOC_VOIDED",
        "BILLING_DOC_CONTINGENCY_RECORDED",
        "BILLING_BRANCH_FISCAL_CONFIG_UPDATED",
        "ACCOUNTING_COA_UPSERTED",
        "ACCOUNTING_FX_RATE_UPSERTED",
        "ACCOUNTING_FX_REVALUATION_EXECUTED",
        "ACCOUNTING_FX_REVALUATION_BLOCKED",
        "ACCOUNTING_INTERCOMPANY_CREATED",
        "ACCOUNTING_INTERCOMPANY_CONFIRMED",
        "ACCOUNTING_INTERCOMPANY_ADJUSTED",
        "ACCOUNTING_INTERCOMPANY_CLOSED",
        "ACCOUNTING_INTERCOMPANY_CYCLE_EXECUTED",
        "ACCOUNTING_CONSOLIDATION_COMPLETED",
        "ACCOUNTING_CONSOLIDATION_BLOCKED",
        "INTERCOMPANY_CHARGE_RECORDED",
        "ACCOUNTING_JOURNAL_APPROVED",
        "ACCOUNTING_JOURNAL_POSTED",
        "ACCOUNTING_JOURNAL_REVERSED",
        "ACCOUNTING_POSTING_BLOCKED",
        "ACCOUNTING_PERIOD_CLOSED",
        "ACCOUNTING_PERIOD_REOPENED",
        "PORTFOLIO_RECEIVABLE_CREATED",
        "PORTFOLIO_RECEIVABLE_ADJUSTED",
        "PORTFOLIO_RECEIVABLE_WRITTEN_OFF",
        "PORTFOLIO_PAYABLE_CREATED",
        "PORTFOLIO_PAYMENT_ALLOCATED",
        "PORTFOLIO_PAYROLL_ABONO_APPLIED",
        "REPORTING_DATASET_EXECUTED",
        "CEC_EXCEPTION_RAISED",
        "CEC_CLOSE_RUN_ADVANCED",
        "PARTY_CREATED",
        "PARTY_UPDATED",
        "PARTY_ROLE_ASSIGNED",
        "PARTY_ROLE_REVOKED",
    }
)

ALLOWED_REASON_CODES: set[str] = {
    # Legacy / compat (mucho código actual usa "OK")
    "OK",
    # OK por módulo (Opción B)
    "AUTH_OK",
    "RBAC_OK",
    "SYNC_OK",
    "ORG_OK",
    "HR_OK",
    "FUEL_OK",
    "AUDIT_OK",
    "REPORTS_OK",
    "FINCA_OK",

    # OK por módulo (futuros kernels)

    # Auth/login
    "INVALID_CREDENTIALS",
    "USER_DISABLED",
    # Tokens
    "TOKEN_INVALID",
    "TOKEN_EXPIRED",
    "TOKEN_MISMATCH",
    "INVALID_OLD_PASSWORD",
    "CSRF_FAILED",
    "TOTP_INVALID",
    "TOTP_REQUIRED",
    # Contrato de errores API (auth)
    "AUTH_UNAUTHENTICATED",
    "AUTH_INVALID_TOKEN",
    "AUTH_TOKEN_EXPIRED",
    # Seguridad
    "RATE_LIMITED",
    # Authorization / policy
    "POLICY_PERMISSION_DENIED",
    "POLICY_SCOPE_DENIED",
    # Contrato de errores API (authz)
    "RBAC_FORBIDDEN",
    "SCOPE_FORBIDDEN",

    # Contrato de errores API (genéricos)
    "BAD_REQUEST",
    "VALIDATION_ERROR",
    "NOT_FOUND",
    "CONFLICT",
    "INTERNAL_ERROR",
    "SERVICE_UNAVAILABLE",

    # FUEL (operación)
    "SHIFT_CLOSED",
    "VOID_NOT_ALLOWED",
    "METER_READING_MISMATCH",
    "INTERNAL_CREDIT_LIMIT",
    # Sync outcomes/errors
    "SYNC_DUPLICATE",
    "SYNC_INVALID_SIGNATURE",
    "SYNC_FORBIDDEN_SCOPE",
    "SYNC_SCHEMA_INVALID",
    "SYNC_DEVICE_REVOKED",
    "SYNC_DEVICE_QUARANTINED",
    "SYNC_PAYLOAD_MISMATCH",
    "SYNC_LIMIT_EXCEEDED",
    "SYNC_TIME_SKEW",
    "SYNC_INTERNAL_ERROR",
    "SYNC_BAD_SIGNATURE",
    "SYNC_REPLAY_DETECTED",
    "SYNC_TS_OUT_OF_WINDOW",
    "SYNC_DEVICE_ID_MISMATCH",
    "SYNC_UNKNOWN_DEVICE",
    "SYNC_DEVICE_NO_HMAC_SECRET",
    "SYNC_DEVICE_NO_PUBLIC_KEY",
    "SYNC_ENROLL_INVALID_CODE",
    "SYNC_ENROLL_EXPIRED_CODE",
    "SYNC_ENROLL_USED_CODE",
    "SYNC_INVALID_PUBLIC_KEY",
    "SYNC_LEGACY_HMAC_DISABLED",
    "SYNC_LEGACY_HMAC_SUNSET",

    # POS via Sync command handlers
    "POS_INVALID_SCOPE",
    "POS_SCHEMA_INVALID",
    "POS_ACTOR_REQUIRED",
    "POS_COMPENSATION_PENDING",

    # INVENTORY (reglas)
    "NEGATIVE_STOCK_BLOCKED",
    "INVENTORY_INVALID_SCOPE",
    "INVENTORY_INSUFFICIENT_STOCK",
    "INVENTORY_IDEMPOTENCY_CONFLICT",
    "INVENTORY_SCHEMA_INVALID",

    # BILLING (reglas)
    "INVOICE_NOT_DRAFT",
    "SERIES_EXHAUSTED",
    "INSECURE_TRANSPORT",
}

# Reason Codes (añadir)
ALLOWED_REASON_CODES.update(
    {
        "INVENTORY_OK",
        "BILLING_OK",
        "BILLING_VOID",
        "BILLING_CONTINGENCY",
        "ACCOUNTING_OK",
        "ACCOUNTING_REVALUATION_BLOCKED",
        "ACCOUNTING_CONFIG_MISSING",
        "ACCOUNTING_INTERCOMPANY_DIFFERENCE",
        "ACCOUNTING_INTERCOMPANY_DISPUTE",
        "ACCOUNTING_CONSOLIDATION_BLOCKED",
        "NOMINA_OK",
        "PAYMENTS_OK",
        "PORTFOLIO_OK",
    }
)

ALLOWED_SUBJECT_TYPES: set[str] = {
    "",
    "USER",
    "SESSION",
    "DEVICE",
    "COMPANY",
    "COMPANY_MODULE",
    "BRANCH",
    "POSITION",
    "EMPLOYEE",

    # FUEL (Estación de Servicios)
    "FUEL_SHIFT",
    "FUEL_DISPENSE",
    "FUEL_SALE",
    "FUEL_TANK",
    "FUEL_NOZZLE",
    "FUEL_PRICE",
    "FUEL_OUTBOX",
    "FUEL_LIQUIDATION",

    # INVENTORY
    "INVENTORY_ITEM",
    "STOCK_MOVEMENT",
    "WAREHOUSE",
    "INVENTORY_LOT",

    # BILLING
    "CUSTOMER",
    "INVOICE",
    "PAYMENT",
    # RETAIL POS
    "POS_SESSION",
    "POS_TICKET",
    "POS_PERIPHERAL",
    # PAYMENTS
    "CASH_MOVEMENT",
}

# Subject Types (añadir)
ALLOWED_SUBJECT_TYPES.update(
    {
        "INVENTORY_MOVEMENT",
        "INVENTORY_TRANSFER",
        "BILLING_DOC",
        "ACCOUNTING_COA",
        "FX_RATE",
        "REVALUATION_RUN",
        "JOURNAL_ENTRY_LINE",
        "JOURNAL_DRAFT",
        "JOURNAL_ENTRY",
        "FISCAL_PERIOD",
        "RECEIVABLE",
        "PAYABLE",
        "CREDIT",
        "LOAN",
        "PAYROLL_LOAN_DEDUCTION",
        "PAYMENT_ALLOCATION",
        "REPORT_RUN",
        "CEC_EXCEPTION",
        "CLOSE_RUN",
        "INTERCOMPANY_TX",
        "CONSOLIDATION_RUN",
        "PARTY",
        "PARTY_ROLE",
        "BILLING_PAYMENT",
        "SALES_ORDER",
        "CREDIT_APPROVAL",
        "NOMINA_CONFIG",
        "PAYROLL_PERIOD",
        "PAYROLL_SHEET",
        "EMPLOYEE_INSS_ENROLLMENT",
        "PAYROLL_INSS_ELECTION",
        "PAYROLL_PAYMENT",
        "FIELD_CREW",
        "FIELD_WORK_DAY",
        "FIELD_CREW_REPORT",
        "FIELD_WORKER_EVENT",
        "ATTENDANCE_REPORT",
        "APPROVAL_REQUEST",
    }
)

# Nomina / Field Attendance
ALLOWED_EVENT_TYPES.update(
    {
        "FIELD_WORK_DAY_OPENED",
        "FIELD_ROLLCALL_SUBMITTED",
        "FIELD_CREW_CREATED",
        "FIELD_CREW_REPORT_SUBMITTED",
        "FIELD_WORKER_EVENT_RECORDED",
        "FIELD_WORKER_TRANSFERRED",
        "FIELD_ATTENDANCE_CONSOLIDATED",
        "FIELD_ATTENDANCE_CONFLICT_RAISED",
        "FIELD_ATTENDANCE_APPROVED",
        "FIELD_ATTENDANCE_LOCKED",
        "FIELD_ATTENDANCE_APPLIED_TO_PAYROLL",
        "FIELD_ATTENDANCE_REPORT_ROLLUP",
    }
)
ALLOWED_REASON_CODES.update(
    {
        "FIELD_ATTENDANCE_OK",
        "FIELD_ATTENDANCE_INVALID_SCOPE",
        "FIELD_ATTENDANCE_INVALID_STATE",
        "FIELD_ATTENDANCE_EMPLOYEE_OUT_OF_SCOPE",
        "FIELD_ATTENDANCE_DUPLICATE_EMPLOYEE",
        "FIELD_ATTENDANCE_BLOCKED_CONFLICT",
        "FIELD_ATTENDANCE_MISSING_REQUIRED_DETAIL",
    }
)
ALLOWED_SUBJECT_TYPES.update(
    {
        "FIELD_WORK_DAY",
        "FIELD_ROLLCALL",
        "FIELD_CREW",
        "FIELD_CREW_REPORT",
        "FIELD_WORKER_EVENT",
        "FIELD_TRANSFER",
        "FIELD_ATTENDANCE_CONSOLIDATION",
        "PAYROLL_ENTRY",
        "ATTENDANCE_REPORT",
    }
)

# IAM / SoD (maker-checker) — Fase 0 fundación
ALLOWED_EVENT_TYPES.update(
    {
        "IAM_APPROVAL_REQUESTED",
        "IAM_APPROVAL_APPROVED",
        "IAM_APPROVAL_REJECTED",
        "IAM_APPROVAL_CANCELLED",
        "IAM_APPROVAL_EXECUTED",
    }
)
ALLOWED_REASON_CODES.update(
    {
        "IAM_OK",
        "SOD_SELF_APPROVAL",
        "APPROVER_NOT_AUTHORIZED",
        "APPROVAL_INVALID_STATE",
    }
)

# RBAC admin (asignación de roles por usuario) — Fase 0 fundación
ALLOWED_EVENT_TYPES.update(
    {
        "RBAC_ROLE_ASSIGNED",
        "RBAC_ROLE_REVOKED",
    }
)
ALLOWED_SUBJECT_TYPES.update({"ROLE_ASSIGNMENT"})

# Billing: nota de crédito (Unidad #1)
ALLOWED_EVENT_TYPES.update({"BILLING_CREDIT_NOTE_ISSUED"})

# Inventory: reversa de movimiento de primera clase (Unidad #2)
ALLOWED_EVENT_TYPES.update({"INVENTORY_MOVEMENT_REVERSED"})

# Inventory: remisiones (despacho + recepción/cotejo con evidencia)
ALLOWED_EVENT_TYPES.update(
    {
        "REMISION_CREATED",
        "REMISION_DISPATCHED",
        "REMISION_RECEIVED",
        "REMISION_CANCELLED",
        "REMISION_PHOTO_ATTACHED",
    }
)
ALLOWED_SUBJECT_TYPES.update({"REMISION"})

# Inventory: política de costo versionada (invariante #8)
ALLOWED_EVENT_TYPES.update({"INVENTORY_COST_POLICY_SET"})
ALLOWED_SUBJECT_TYPES.update({"INVENTORY_COST_POLICY"})
ALLOWED_SUBJECT_TYPES.update({"INTERCOMPANY_TX"})

# Inventory: clase de inventario por producto (FEFO/FIFO/AVERAGE)
ALLOWED_EVENT_TYPES.update({"INVENTORY_ITEM_RECLASSIFIED"})

# Payments: ciclo de caja, intent y diferencias (Unidad #3)
ALLOWED_EVENT_TYPES.update(
    {
        "PAYMENTS_CASH_SESSION_OPENED",
        "PAYMENTS_CASH_SESSION_CLOSED",
        "PAYMENTS_CASH_SESSION_REOPENED",
        "PAYMENTS_CASH_DIFFERENCE_DETECTED",
        "PAYMENTS_INTENT_AUTHORIZED",
        "PAYMENTS_INTENT_CAPTURED",
        "PAYMENTS_INTENT_REVERSED",
        "PAYMENTS_INTENT_CANCELLED",
        "PAYMENTS_INTENT_REFUNDED",
    }
)
ALLOWED_SUBJECT_TYPES.update({"CASH_SESSION", "PAYMENT_INTENT"})

# CONTROLS (Capa 3: anti-fraude / SoD)
ALLOWED_EVENT_TYPES.update(
    {"CONTROL_FINDING_RAISED", "CONTROL_FINDING_RESOLVED", "SEGREGATION_RULES_SEEDED"}
)
ALLOWED_SUBJECT_TYPES.update({"CONTROL_FINDING", "SEGREGATION_RULE"})

# Comisariato: tienda de la empresa que vende a crédito (cuenta + venta + cobro por planilla)
ALLOWED_EVENT_TYPES.update(
    {
        "COMISARIATO_ACCOUNT_UPSERTED",
        "COMISARIATO_CREDIT_SALE",
        "COMISARIATO_STORE_CREDIT_DEDUCTED",
    }
)
ALLOWED_REASON_CODES.update({"COMISARIATO_OK", "COMISARIATO_CREDIT_LIMIT_EXCEEDED"})
ALLOWED_SUBJECT_TYPES.update({"COMISARIATO_ACCOUNT", "COMISARIATO_SALE"})

# Fleet / Mantenimiento (Fase A): activos, conductores, documentos, medidor
ALLOWED_EVENT_TYPES.update(
    {
        "FLEET_ASSET_UPSERTED",
        "FLEET_DRIVER_UPSERTED",
        "FLEET_DRIVER_ASSIGNED",
        "FLEET_DOCUMENT_REGISTERED",
        "FLEET_METER_RECORDED",
    }
)
ALLOWED_REASON_CODES.update(
    {"FLEET_OK", "FLEET_SCHEMA_INVALID", "FLEET_INVALID_SCOPE", "FLEET_NOT_FOUND"}
)
ALLOWED_SUBJECT_TYPES.update({"FLEET_ASSET", "FLEET_DRIVER", "FLEET_DOCUMENT"})

# FINCA (Capa 6: manejo de fincas)
ALLOWED_EVENT_TYPES.update(
    {
        "FINCA_PROFILE_UPSERTED",
        "FINCA_PLOT_CREATED",
        "FINCA_PLOT_UPDATED",
        "FINCA_LABOR_CREATED",
        "FINCA_WORKORDER_LOGGED",
        "FINCA_INSUMO_APPLIED",
        "FINCA_INSUMO_ISSUED",
        "FINCA_COST_POSTED",
    }
)
ALLOWED_SUBJECT_TYPES.update({"FINCA", "FINCA_PLOT", "FINCA_LABOR", "FINCA_WORKORDER"})
# Reject reason codes para los handlers de sync offline de finca (sync_engine).
ALLOWED_REASON_CODES.update({"FINCA_SCHEMA_INVALID", "FINCA_INVALID_SCOPE", "FINCA_NOT_FOUND"})

# Procurement (compras): ciclo del documento de compra (CxP / pasivo)
ALLOWED_EVENT_TYPES.update(
    {"PROCUREMENT_DOC_DRAFTED", "PROCUREMENT_DOC_POSTED", "PROCUREMENT_DOC_VOIDED"}
)
ALLOWED_REASON_CODES.update({"PROCUREMENT_OK"})
ALLOWED_SUBJECT_TYPES.update({"PROCUREMENT_DOC"})

# Reporting: egress (export) y materialización (snapshot) de datos
ALLOWED_EVENT_TYPES.update({"REPORTING_EXPORT_CREATED", "REPORTING_SNAPSHOT_GENERATED"})
ALLOWED_SUBJECT_TYPES.update({"REPORT_EXPORT", "REPORT_SNAPSHOT"})

# Dashboard: acuñación / canje de embed tokens (credencial de acceso)
ALLOWED_EVENT_TYPES.update({"DASHBOARD_EMBED_TOKEN_MINTED", "DASHBOARD_EMBED_TOKEN_REDEEMED"})
ALLOWED_REASON_CODES.update({"DASHBOARD_OK"})
ALLOWED_SUBJECT_TYPES.update({"DASHBOARD_EMBED"})

# Notifications: registro de device token (push)
ALLOWED_EVENT_TYPES.update({"NOTIF_DEVICE_REGISTERED"})
ALLOWED_REASON_CODES.update({"NOTIF_OK"})
ALLOWED_SUBJECT_TYPES.update({"NOTIF_DEVICE"})


def validate_event_type(event_type: str) -> None:
    if event_type not in ALLOWED_EVENT_TYPES:
        raise ValueError(f"event_type no permitido: {event_type}")


def validate_reason_code(reason_code: str) -> None:
    if reason_code == "":
        return
    if reason_code not in ALLOWED_REASON_CODES:
        raise ValueError(f"reason_code no permitido: {reason_code}")


def validate_subject(subject_type: str, subject_id: str) -> None:
    if subject_type not in ALLOWED_SUBJECT_TYPES:
        raise ValueError(f"subject_type no permitido: {subject_type}")
    # subject_id puede ser "" en algunos eventos (por ejemplo cuando no existe info suficiente).
    # Para USER/SESSION/DEVICE normalmente conviene que venga lleno, pero no forzamos en DB.
