# Generated by Django 5.2.12 on 2026-03-25 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0002_outbox_next_attempt_at'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='inboxevent',
            new_name='integration_consume_253f49_idx',
            old_name='integratio_consume_6ab9e4_idx',
        ),
        migrations.RenameIndex(
            model_name='outboxevent',
            new_name='integration_status_ecb22f_idx',
            old_name='integratio_status_43d458_idx',
        ),
        migrations.RenameIndex(
            model_name='outboxevent',
            new_name='integration_status_585d30_idx',
            old_name='integratio_status_3ec52d_idx',
        ),
        migrations.RenameIndex(
            model_name='outboxevent',
            new_name='integration_source__51f6df_idx',
            old_name='integratio_source__7f8f5f_idx',
        ),
    ]
