# Generated by Django 5.2.12 on 2026-03-25 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0003_orgunit_parent_type_name_idx'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='orgunit',
            new_name='iam_orgunit_parent__f0840d_idx',
            old_name='iam_orgunit_parent_type_name_idx',
        ),
    ]
