# Generated by Django 5.2.12 on 2026-03-25 16:21

from django.conf import settings
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('accounting', '0009_rename_acc_coa_comp_type_act_idx_accounting__company_41d161_idx_and_more'),
        ('facturacion', '0004_billingdocument_source_refs'),
        ('iam', '0004_rename_iam_orgunit_parent_type_name_idx_iam_orgunit_parent__f0840d_idx'),
        ('inventarios', '0002_stockmovement_accounting_links'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='billingdocument',
            new_name='facturacion_company_e59730_idx',
            old_name='facturacion_company_99f3f6_idx',
        ),
        migrations.RenameIndex(
            model_name='billingdocument',
            new_name='facturacion_company_86fb84_idx',
            old_name='modulos_fac_company_2f0a22_idx',
        ),
        migrations.RenameIndex(
            model_name='branchfiscalconfig',
            new_name='facturacion_company_81ec01_idx',
            old_name='facturacion_company_ba6c83_idx',
        ),
        migrations.RenameIndex(
            model_name='fiscalprintjob',
            new_name='facturacion_status_9eacdb_idx',
            old_name='facturacion_status_55e93e_idx',
        ),
        migrations.RenameIndex(
            model_name='fiscalprintjob',
            new_name='facturacion_company_3f8672_idx',
            old_name='facturacion_company_e8dd3b_idx',
        ),
        AddIndexConcurrently(
            model_name='billingdocument',
            index=models.Index(fields=['company', 'branch', 'created_at'], name='facturacion_company_25ee6a_idx'),
        ),
        AddIndexConcurrently(
            model_name='billingdocument',
            index=models.Index(fields=['company', 'branch', 'doc_type', 'status', 'created_at'], name='facturacion_company_3a19e3_idx'),
        ),
        AddIndexConcurrently(
            model_name='billingdocument',
            index=models.Index(fields=['company', 'idempotency_key'], name='facturacion_company_d0dea3_idx'),
        ),
        AddIndexConcurrently(
            model_name='billingline',
            index=models.Index(fields=['doc'], name='facturacion_doc_id_8aa04b_idx'),
        ),
    ]
