# Generated by Django 5.2.12 on 2026-05-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_rename_facturacion_company_99f3f6_idx_facturacion_company_e59730_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdocument',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('', 'Unknown / historical'), ('CASH', 'Cash'), ('TRANSFER', 'Transfer'), ('CREDIT', 'Credit'), ('CARD', 'Card')], default='', max_length=16),
        ),
    ]
