# Generated by Django 5.2.9 on 2026-06-02 21:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_posting_ruleset_rule_family'),
        ('facturacion', '0007_billingdocument_customer_party'),
        ('iam', '0004_rename_iam_orgunit_parent_type_name_idx_iam_orgunit_parent__f0840d_idx'),
        ('inventarios', '0004_itemlot_lotbalance_and_more'),
        ('parties', '0001_initial'),
        ('payments', '0005_alter_paymentintent_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('', 'Sin especificar'), ('CASH', 'Efectivo'), ('TRANSFER', 'Transferencia Bancaria'), ('CREDIT', 'Crédito'), ('CARD', 'Tarjeta'), ('CHECK', 'Cheque'), ('PAYROLL_DEDUCTION', 'Descuento de Nómina'), ('PRODUCER_CREDIT', 'Crédito Productor (Café)'), ('INTERNAL_TRANSFER', 'Traslado Interno'), ('COFFEE_QUOTA', 'Cuota de Café (especie)'), ('MIXED', 'Mixto')], max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='NIO', max_length=8)),
                ('reference', models.CharField(blank=True, default='', max_length=96)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmado'), ('REVERSED', 'Revertido')], db_index=True, default='PENDING', max_length=12)),
                ('reversal_reason', models.CharField(blank=True, default='', max_length=255)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('payroll_period_ref', models.CharField(blank=True, default='', max_length=64)),
                ('coffee_lot_ref', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='CreditApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_REVIEW', 'En revisión'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado'), ('ESCALATED', 'Escalado'), ('CANCELLED', 'Cancelado')], db_index=True, default='PENDING', max_length=16)),
                ('level', models.CharField(choices=[('SALES_MANAGER', 'Gerente de Ventas'), ('CREDIT_COMMITTEE', 'Comité de Crédito'), ('CEO', 'Gerencia General')], db_index=True, default='SALES_MANAGER', max_length=24)),
                ('amount_requested', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('currency', models.CharField(default='NIO', max_length=8)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('request_notes', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('approved_terms_days', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('PENDING_APPROVAL', 'Pendiente de aprobación'), ('IN_REVIEW', 'En revisión'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado'), ('PURCHASE_ORDERED', 'Orden de compra emitida'), ('PURCHASE_RECEIVED', 'Mercancía recibida'), ('READY', 'Listo para despachar'), ('FULFILLED', 'Despachado y facturado'), ('CANCELLED', 'Cancelado')], db_index=True, default='DRAFT', max_length=24)),
                ('customer_type', models.CharField(choices=[('WORKER', 'Trabajador de la empresa'), ('PRODUCER_FINANCED', 'Productor en financiamiento'), ('EXTERNAL', 'Cliente externo'), ('INTERNAL', 'Traslado interno')], default='EXTERNAL', max_length=24)),
                ('customer_name', models.CharField(blank=True, default='', max_length=160)),
                ('customer_ref', models.CharField(blank=True, default='', max_length=64)),
                ('currency', models.CharField(default='NIO', max_length=8)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('credit_status', models.CharField(choices=[('NONE', 'No requiere crédito'), ('PENDING_REVIEW', 'Pendiente de revisión'), ('IN_REVIEW', 'En revisión'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado'), ('ESCALATED', 'Escalado a gerencia')], db_index=True, default='NONE', max_length=16)),
                ('credit_notes', models.TextField(blank=True, default='')),
                ('credit_approved_at', models.DateTimeField(blank=True, null=True)),
                ('purchase_order_ref', models.CharField(blank=True, default='', max_length=96)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=18)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=8)),
                ('discount_pct', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=6)),
                ('line_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('line_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('qty_available_snapshot', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Stock disponible al crear la orden', max_digits=18)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='billingdocument',
            name='uniq_bill_number',
        ),
        migrations.RenameIndex(
            model_name='billingdocument',
            new_name='ix_billdoc_c_b_ca',
            old_name='facturacion_company_25ee6a_idx',
        ),
        migrations.RenameIndex(
            model_name='billingdocument',
            new_name='ix_billdoc_c_b_t_s_ca',
            old_name='facturacion_company_3a19e3_idx',
        ),
        migrations.RenameIndex(
            model_name='billingdocument',
            new_name='ix_billdoc_c_idem',
            old_name='facturacion_company_d0dea3_idx',
        ),
        migrations.RenameIndex(
            model_name='billingdocument',
            new_name='ix_billdoc_co_cust_party',
            old_name='ix_bill_doc_co_cust_party',
        ),
        migrations.RenameIndex(
            model_name='billingdocument',
            new_name='ix_billdoc_fiscal',
            old_name='facturacion_company_e59730_idx',
        ),
        migrations.RenameIndex(
            model_name='billingdocument',
            new_name='ix_billdoc_acc_st',
            old_name='facturacion_company_86fb84_idx',
        ),
        migrations.RenameIndex(
            model_name='billingline',
            new_name='ix_billine_doc',
            old_name='facturacion_doc_id_8aa04b_idx',
        ),
        migrations.RenameIndex(
            model_name='branchfiscalconfig',
            new_name='ix_billfcfg_c_b_a',
            old_name='facturacion_company_81ec01_idx',
        ),
        migrations.RenameIndex(
            model_name='fiscalprintjob',
            new_name='ix_billfpj_st_na_ca',
            old_name='facturacion_status_9eacdb_idx',
        ),
        migrations.RenameIndex(
            model_name='fiscalprintjob',
            new_name='ix_billfpj_c_b_st_ca',
            old_name='facturacion_company_3f8672_idx',
        ),
        migrations.AddField(
            model_name='billingdocument',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddField(
            model_name='billingdocument',
            name='credit_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billingdocument',
            name='credit_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_docs_credit_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billingdocument',
            name='credit_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='billingdocument',
            name='credit_status',
            field=models.CharField(choices=[('NONE', 'No requiere crédito'), ('PENDING_REVIEW', 'Pendiente de revisión'), ('IN_REVIEW', 'En revisión'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado'), ('ESCALATED', 'Escalado a gerencia')], db_index=True, default='NONE', max_length=16),
        ),
        migrations.AddField(
            model_name='billingdocument',
            name='customer_type',
            field=models.CharField(choices=[('WORKER', 'Trabajador de la empresa'), ('PRODUCER_FINANCED', 'Productor en financiamiento'), ('EXTERNAL', 'Cliente externo'), ('INTERNAL', 'Traslado interno')], db_index=True, default='EXTERNAL', max_length=24),
        ),
        migrations.AddField(
            model_name='billingdocument',
            name='discount_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddField(
            model_name='billingdocument',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Sin pagar'), ('PARTIAL', 'Pago parcial'), ('PAID', 'Pagada'), ('OVERPAID', 'Sobrepago')], db_index=True, default='UNPAID', max_length=12),
        ),
        migrations.AddField(
            model_name='billingdocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='billingline',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddField(
            model_name='billingline',
            name='discount_pct',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Descuento en % (ej. 10.0000 = 10%)', max_digits=6),
        ),
        migrations.AddField(
            model_name='billingline',
            name='line_gross',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddField(
            model_name='billingline',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_lines', to='inventarios.itemlot'),
        ),
        migrations.AddField(
            model_name='billingline',
            name='uom',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='billingline',
            name='uom_factor',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=14),
        ),
        migrations.AddField(
            model_name='billingline',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_lines', to='inventarios.warehouse'),
        ),
        migrations.AlterField(
            model_name='billingdocument',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='billingdocument',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_docs_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='billingdocument',
            name='doc_type',
            field=models.CharField(choices=[('INVOICE', 'Factura'), ('CREDIT_NOTE', 'Nota de Crédito'), ('QUOTE', 'Cotización / Proforma'), ('ORDER', 'Orden de Venta (por encargo)')], max_length=16),
        ),
        migrations.AlterField(
            model_name='billingdocument',
            name='fiscal_mode_resolved',
            field=models.CharField(choices=[('NOOP', 'Sin fiscal'), ('A', 'Adapter A'), ('B', 'Adapter B')], default='NOOP', max_length=8),
        ),
        migrations.AlterField(
            model_name='billingdocument',
            name='fiscal_status',
            field=models.CharField(blank=True, choices=[('NUMBER_RESERVED', 'Número reservado'), ('ISSUED', 'Emitida'), ('PRINTED', 'Impresa'), ('FAILED_PRINT', 'Error de impresión'), ('CONTINGENCY', 'Contingencia'), ('VOIDED', 'Anulada')], default='', max_length=24),
        ),
        migrations.AlterField(
            model_name='billingdocument',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('', 'Sin especificar'), ('CASH', 'Efectivo'), ('TRANSFER', 'Transferencia Bancaria'), ('CREDIT', 'Crédito'), ('CARD', 'Tarjeta'), ('CHECK', 'Cheque'), ('PAYROLL_DEDUCTION', 'Descuento de Nómina'), ('PRODUCER_CREDIT', 'Crédito Productor (Café)'), ('INTERNAL_TRANSFER', 'Traslado Interno'), ('COFFEE_QUOTA', 'Cuota de Café (especie)'), ('MIXED', 'Mixto')], default='', max_length=24),
        ),
        migrations.AlterField(
            model_name='billingdocument',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('ISSUED', 'Emitida'), ('VOIDED', 'Anulada')], db_index=True, default='DRAFT', max_length=16),
        ),
        migrations.AlterField(
            model_name='billingsequence',
            name='doc_type',
            field=models.CharField(choices=[('INVOICE', 'Factura'), ('CREDIT_NOTE', 'Nota de Crédito'), ('QUOTE', 'Cotización / Proforma'), ('ORDER', 'Orden de Venta (por encargo)')], max_length=16),
        ),
        migrations.AlterField(
            model_name='billingsequence',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='branchfiscalconfig',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='branchfiscalconfig',
            name='fiscal_mode',
            field=models.CharField(choices=[('NOOP', 'Sin fiscal'), ('A', 'Adapter A'), ('B', 'Adapter B')], default='NOOP', max_length=8),
        ),
        migrations.AlterField(
            model_name='fiscalprintjob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('RETRY', 'Reintento'), ('PRINTED', 'Impreso'), ('FAILED', 'Fallido')], default='PENDING', max_length=16),
        ),
        migrations.AddIndex(
            model_name='billingdocument',
            index=models.Index(fields=['company', 'payment_status', 'created_at'], name='ix_billdoc_pay_st'),
        ),
        migrations.AddIndex(
            model_name='billingdocument',
            index=models.Index(fields=['company', 'credit_status'], name='ix_billdoc_crs'),
        ),
        migrations.AddIndex(
            model_name='billingdocument',
            index=models.Index(fields=['company', 'customer_type', 'created_at'], name='ix_billdoc_ctype'),
        ),
        migrations.AddConstraint(
            model_name='billingdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('number', 0), _negated=True), fields=('company', 'branch', 'doc_type', 'series', 'number'), name='uniq_bill_number'),
        ),
        migrations.AddField(
            model_name='billingpayment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_payments_company', to='iam.orgunit'),
        ),
        migrations.AddField(
            model_name='billingpayment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_payments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billingpayment',
            name='doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='facturacion.billingdocument'),
        ),
        migrations.AddField(
            model_name='billingpayment',
            name='payment_intent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_payments', to='payments.paymentintent'),
        ),
        migrations.AddField(
            model_name='billingpayment',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_payments_reversed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditapprovalrequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_requests_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditapprovalrequest',
            name='billing_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_approvals', to='facturacion.billingdocument'),
        ),
        migrations.AddField(
            model_name='creditapprovalrequest',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_approvals_company', to='iam.orgunit'),
        ),
        migrations.AddField(
            model_name='creditapprovalrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_requests_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditapprovalrequest',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_requests_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='billing_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_sales_orders', to='facturacion.billingdocument'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders_branch', to='iam.orgunit'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders_company', to='iam.orgunit'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='credit_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders_credit_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='customer_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='parties.party'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditapprovalrequest',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_approvals', to='facturacion.salesorder'),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_lines', to='inventarios.inventoryitem'),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='facturacion.salesorder'),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='preferred_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_order_lines', to='inventarios.warehouse'),
        ),
        migrations.AddIndex(
            model_name='billingpayment',
            index=models.Index(fields=['doc', 'status'], name='ix_billpay_doc_st'),
        ),
        migrations.AddIndex(
            model_name='billingpayment',
            index=models.Index(fields=['company', 'payment_method', 'payment_date'], name='ix_billpay_c_pm_pd'),
        ),
        migrations.AddIndex(
            model_name='billingpayment',
            index=models.Index(fields=['company', 'status', 'created_at'], name='ix_billpay_c_st_ca'),
        ),
        migrations.AddConstraint(
            model_name='billingpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_billpay_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['company', 'status', 'created_at'], name='ix_so_c_st_ca'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['company', 'customer_party', 'status'], name='ix_so_c_cp_st'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['company', 'credit_status'], name='ix_so_c_crs'),
        ),
        migrations.AddIndex(
            model_name='creditapprovalrequest',
            index=models.Index(fields=['company', 'status', 'level'], name='ix_cra_c_st_lv'),
        ),
        migrations.AddIndex(
            model_name='creditapprovalrequest',
            index=models.Index(fields=['assigned_to', 'status'], name='ix_cra_at_st'),
        ),
        migrations.AddIndex(
            model_name='creditapprovalrequest',
            index=models.Index(fields=['company', 'requested_at'], name='ix_cra_c_ra'),
        ),
    ]
