# Generated by Django 5.2.12 on 2026-06-03 18:37

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0008_billingpayment_creditapprovalrequest_salesorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdocument',
            name='credited_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddField(
            model_name='billingdocument',
            name='related_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes_of', to='facturacion.billingdocument'),
        ),
    ]
