# Generated by Django 5.2.12 on 2026-03-25 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_employmentassignment_employee_active_started_idx'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='employmentassignment',
            new_name='hr_employme_employe_4b785a_idx',
            old_name='hr_employassign_emp_active_start_idx',
        ),
    ]
