# Generated by Django 5.2.12 on 2026-06-10 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_employee_party'),
        ('rbac', '0006_materialize_global_userroles'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRoleMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_maps', to='hr.employee')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_maps', to='rbac.role')),
            ],
            options={
                'indexes': [models.Index(fields=['employee', 'is_active'], name='hr_employee_employe_9a48e4_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'role'), name='uq_employee_role')],
            },
        ),
    ]
