# Generated by Django 5.2.12 on 2026-06-10 22:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_employeerolemap'),
        ('iam', '0005_approvalrequest'),
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLifecycleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('SUSPENSION', 'Suspensión'), ('REINTEGRO', 'Reintegro'), ('BAJA', 'Baja'), ('REINGRESO', 'Reingreso')], max_length=16)),
                ('reason_code', models.CharField(blank=True, default='', max_length=32)),
                ('reason_detail', models.TextField(blank=True, default='')),
                ('effective_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('with_pay', models.BooleanField(default=False)),
                ('access_suspended', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo_type', models.CharField(choices=[('MEMORANDO', 'Memorando'), ('AMONESTACION_VERBAL', 'Amonestación verbal (constancia)'), ('AMONESTACION_ESCRITA', 'Amonestación escrita'), ('FELICITACION', 'Felicitación / reconocimiento'), ('ACUERDO', 'Acta de acuerdo'), ('OTRO', 'Otro')], default='MEMORANDO', max_length=32)),
                ('status', models.CharField(choices=[('EMITIDO', 'Emitido'), ('ANULADO', 'Anulado')], default='EMITIDO', max_length=16)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('issued_date', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ['-issued_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EmploymentContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('INDEFINIDO', 'Tiempo indefinido'), ('PLAZO_FIJO', 'Plazo fijo / determinado'), ('OBRA', 'Por obra o servicio determinado'), ('TEMPORADA', 'Por temporada (cosecha)')], max_length=16)),
                ('status', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EMITIDO', 'Emitido'), ('FINALIZADO', 'Finalizado'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=16)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('salary_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_period', models.CharField(choices=[('MENSUAL', 'Mensual'), ('QUINCENAL', 'Quincenal'), ('SEMANAL', 'Semanal'), ('DIARIO', 'Diario'), ('POR_OBRA', 'Por obra / producción')], default='MENSUAL', max_length=16)),
                ('body', models.TextField(blank=True, default='')),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='employment_status',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido'), ('BAJA', 'Baja')], default='ACTIVO', max_length=16),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['company', 'employment_status'], name='hr_employee_company_8c1b53_idx'),
        ),
        migrations.AddField(
            model_name='employeelifecycleevent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_lifecycle_events_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeelifecycleevent',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_events', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='employeememo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_memos_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeememo',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memos', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='employmentcontract',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_contracts_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employmentcontract',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='employmentcontract',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='hr.jobposition'),
        ),
        migrations.AddIndex(
            model_name='employeelifecycleevent',
            index=models.Index(fields=['employee', 'created_at'], name='hr_employee_employe_00fbc7_idx'),
        ),
        migrations.AddIndex(
            model_name='employeelifecycleevent',
            index=models.Index(fields=['employee', 'event_type'], name='hr_employee_employe_c5411d_idx'),
        ),
        migrations.AddIndex(
            model_name='employeememo',
            index=models.Index(fields=['employee', 'status'], name='hr_employee_employe_0a0638_idx'),
        ),
        migrations.AddIndex(
            model_name='employeememo',
            index=models.Index(fields=['employee', 'memo_type'], name='hr_employee_employe_3f7537_idx'),
        ),
        migrations.AddIndex(
            model_name='employmentcontract',
            index=models.Index(fields=['employee', 'status'], name='hr_employme_employe_ec532d_idx'),
        ),
        migrations.AddIndex(
            model_name='employmentcontract',
            index=models.Index(fields=['status', 'end_date'], name='hr_employme_status_5d9e90_idx'),
        ),
    ]
