# Generated by Django 5.2.12 on 2026-06-11 16:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_employeelifecycleevent_employeememo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cedula',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='daily_rate_nio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Jornal diario C$ (si salary_type=DAILY)', max_digits=18),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='employee',
            name='inss_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='monthly_salary_nio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Salario mensual C$ (si salary_type=MONTHLY)', max_digits=18),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_type',
            field=models.CharField(choices=[('DAILY', 'Por día (jornal)'), ('MONTHLY', 'Mensual')], default='DAILY', max_length=10),
        ),
    ]
