# Generated by Django 5.2.12 on 2026-03-25 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estacion_servicios', '0009_fuelsale_compensation_state'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fueldispense',
            new_name='estacion_se_company_54b2c6_idx',
            old_name='estacion_se_company__c8e61a_idx',
        ),
        migrations.RenameIndex(
            model_name='fueldispense',
            new_name='estacion_se_shift_i_ded7f6_idx',
            old_name='estacion_se_shift_i_2b6c2f_idx',
        ),
        migrations.RenameIndex(
            model_name='fueldispense',
            new_name='estacion_se_product_dd2d13_idx',
            old_name='estacion_se_product_4fd987_idx',
        ),
        migrations.RenameIndex(
            model_name='fuelsale',
            new_name='estacion_se_company_833b49_idx',
            old_name='estacion_se_company__8d6f1d_idx',
        ),
        migrations.RenameIndex(
            model_name='fuelsale',
            new_name='estacion_se_status_8ab933_idx',
            old_name='estacion_se_status__aeb1f0_idx',
        ),
        migrations.RenameIndex(
            model_name='fuelsale',
            new_name='estacion_se_status_e5b15d_idx',
            old_name='fuel_sale_comp_retry_idx',
        ),
        migrations.RenameIndex(
            model_name='fuelshift',
            new_name='estacion_se_company_5af039_idx',
            old_name='estacion_se_company__7aa2c2_idx',
        ),
        migrations.RenameIndex(
            model_name='fueluompreference',
            new_name='estacion_se_company_36c47d_idx',
            old_name='idx_fuel_uom_pref_scope',
        ),
        migrations.RenameIndex(
            model_name='fueluompreference',
            new_name='estacion_se_company_dd3b94_idx',
            old_name='idx_fuel_uom_pref_branch_prod',
        ),
    ]
