# Generated by Codex on 2026-05-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estacion_servicios", "0010_rename_estacion_se_company__c8e61a_idx_estacion_se_company_54b2c6_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fuelsale",
            name="idempotency_key",
            field=models.CharField(blank=True, default="", max_length=96),
        ),
        migrations.AddConstraint(
            model_name="fuelsale",
            constraint=models.UniqueConstraint(
                condition=~models.Q(idempotency_key=""),
                fields=("company", "idempotency_key"),
                name="uq_fuel_sale_company_idempotency",
            ),
        ),
    ]
