# Generated by Django 5.2.12 on 2026-06-13 19:03

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacion_servicios', '0012_fuelsale_customer_party'),
        ('iam', '0005_approvalrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelTank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('product', models.CharField(choices=[('DIESEL', 'Diesel'), ('GASOLINE', 'Gasolina')], max_length=16)),
                ('capacity_l', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('current_volume_l', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('low_level_l', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Umbral para alertar nivel bajo (0 = sin alerta).', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_tanks_branch', to='iam.orgunit')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_tanks_company', to='iam.orgunit')),
            ],
        ),
        migrations.CreateModel(
            name='FuelTankMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('RECEIPT', 'Recepción'), ('DISPENSE', 'Despacho'), ('ADJUSTMENT', 'Ajuste')], max_length=12)),
                ('liters', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('supplier_name', models.CharField(blank=True, default='', max_length=200)),
                ('document_ref', models.CharField(blank=True, default='', max_length=96)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_tank_movements', to=settings.AUTH_USER_MODEL)),
                ('dispense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tank_movements', to='estacion_servicios.fueldispense')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='estacion_servicios.fueltank')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='fueltank',
            index=models.Index(fields=['company', 'branch', 'is_active'], name='estacion_se_company_8b8f37_idx'),
        ),
        migrations.AddConstraint(
            model_name='fueltank',
            constraint=models.UniqueConstraint(fields=('branch', 'code'), name='uq_fuel_tank_branch_code'),
        ),
        migrations.AddConstraint(
            model_name='fueltank',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('branch', 'product'), name='uq_fuel_tank_active_branch_product'),
        ),
        migrations.AddIndex(
            model_name='fueltankmovement',
            index=models.Index(fields=['tank', 'occurred_at'], name='estacion_se_tank_id_6810ea_idx'),
        ),
        migrations.AddIndex(
            model_name='fueltankmovement',
            index=models.Index(fields=['tank', 'kind'], name='estacion_se_tank_id_acb812_idx'),
        ),
    ]
