# Generated by Django 6.0.6 on 2026-06-10 01:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iam', '0005_approvalrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScannedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('GENERAL', 'General'), ('INVOICE', 'Factura/Recibo'), ('FUEL_TICKET', 'Ticket de combustible'), ('PAYROLL', 'Planilla/Nómina')], default='GENERAL', max_length=32)),
                ('status', models.CharField(choices=[('PENDING_OCR', 'Pendiente de OCR'), ('PROCESSED', 'Procesado (OCR)'), ('REVIEWED', 'Revisado'), ('FAILED', 'Falló OCR')], default='PENDING_OCR', max_length=16)),
                ('storage_backend', models.CharField(default='db', max_length=16)),
                ('image_data', models.TextField(blank=True, default='')),
                ('image_ref', models.CharField(blank=True, default='', max_length=512)),
                ('content_type', models.CharField(blank=True, default='', max_length=64)),
                ('byte_size', models.PositiveIntegerField(default=0)),
                ('ocr_text', models.TextField(blank=True, default='')),
                ('extracted_fields', models.JSONField(blank=True, default=dict)),
                ('ocr_engine', models.CharField(blank=True, default='', max_length=32)),
                ('ocr_error', models.CharField(blank=True, default='', max_length=255)),
                ('linked_object_type', models.CharField(blank=True, default='', max_length=64)),
                ('linked_object_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branch_scanned_documents', to='iam.orgunit')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scanned_documents', to='iam.orgunit')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='documents_s_company_819ca4_idx'), models.Index(fields=['company', 'doc_type'], name='documents_s_company_ad1c0d_idx')],
            },
        ),
    ]
