# Generated by Django 5.2.12 on 2026-06-11 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanneddocument',
            name='status',
            field=models.CharField(choices=[('PENDING_OCR', 'Pendiente de OCR'), ('PROCESSED', 'Procesado (OCR)'), ('EXTRACTED', 'Campos extraídos (borrador, pendiente de revisión)'), ('REVIEWED', 'Revisado'), ('FAILED', 'Falló OCR')], default='PENDING_OCR', max_length=16),
        ),
    ]
