# Generated by Django 5.2.12 on 2026-06-11 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_scanneddocument_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanneddocument',
            name='doc_type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('INVOICE', 'Factura/Recibo'), ('FUEL_TICKET', 'Ticket de combustible'), ('PAYROLL', 'Planilla/Nómina'), ('REMISION', 'Remisión/Envío (movimiento entre fincas/bodegas)')], default='GENERAL', max_length=32),
        ),
    ]
