# Generated by Django 5.2.12 on 2026-06-03 03:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_purchasedocument_supplier_party'),
        ('iam', '0004_rename_iam_orgunit_parent_type_name_idx_iam_orgunit_parent__f0840d_idx'),
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='purchasedocument',
            name='uniq_proc_number',
        ),
        migrations.AddConstraint(
            model_name='purchasedocument',
            constraint=models.UniqueConstraint(condition=models.Q(('number__gt', 0)), fields=('company', 'branch', 'doc_type', 'series', 'number'), name='uniq_proc_number'),
        ),
    ]
