# Generated by Django 5.2.12 on 2026-06-09 00:38

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0005_employee_party'),
        ('iam', '0005_approvalrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160)),
                ('national_id', models.CharField(blank=True, default='', max_length=32)),
                ('license_number', models.CharField(blank=True, default='', max_length=64)),
                ('license_category', models.CharField(blank=True, default='', max_length=16)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('SUSPENDED', 'Suspendido'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fleet_drivers', to='iam.orgunit')),
                ('employee', models.ForeignKey(blank=True, help_text='Opcional: enlaza al empleado; null = conductor externo/contratista.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fleet_driver_profiles', to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='FleetAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('VEHICLE', 'Vehículo'), ('MACHINERY', 'Maquinaria'), ('STATIONARY', 'Estacionario')], max_length=12)),
                ('code', models.CharField(help_text='Número/código interno del activo.', max_length=64)),
                ('name', models.CharField(max_length=160)),
                ('plate', models.CharField(blank=True, default='', max_length=32)),
                ('vin', models.CharField(blank=True, default='', max_length=64)),
                ('make', models.CharField(blank=True, default='', max_length=80)),
                ('model', models.CharField(blank=True, default='', max_length=80)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('engine_desc', models.CharField(blank=True, default='', max_length=160)),
                ('fuel_type', models.CharField(choices=[('DIESEL', 'Diésel'), ('GASOLINE', 'Gasolina'), ('NONE', 'N/A')], default='DIESEL', max_length=10)),
                ('tank_capacity_l', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('meter_basis', models.CharField(choices=[('ODOMETER_KM', 'Odómetro (km)'), ('HOURMETER', 'Horómetro (h)')], default='ODOMETER_KM', max_length=12)),
                ('current_odometer_km', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('current_hourmeter', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('has_obd', models.BooleanField(default=False)),
                ('obd_protocol', models.CharField(choices=[('NONE', 'Sin OBD'), ('OBD2_12V', 'OBD-II 12V'), ('J1939_24V', 'J1939 24V')], default='NONE', max_length=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('IN_SERVICE', 'En servicio'), ('MAINTENANCE_DUE', 'Mantenimiento vencido'), ('IN_MAINTENANCE', 'En mantenimiento'), ('OUT_OF_SERVICE', 'Fuera de servicio'), ('RETIRED', 'De baja')], db_index=True, default='ACTIVE', max_length=16)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fleet_assets_branch', to='iam.orgunit')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fleet_assets', to='iam.orgunit')),
            ],
        ),
        migrations.CreateModel(
            name='DriverAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='fleet.driver')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_assignments', to='fleet.fleetasset')),
            ],
        ),
        migrations.CreateModel(
            name='FleetDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('INSURANCE', 'Seguro'), ('CIRCULATION', 'Circulación'), ('LICENSE', 'Licencia'), ('TECH_REVIEW', 'Revisión técnica'), ('OTHER', 'Otro')], max_length=16)),
                ('number', models.CharField(blank=True, default='', max_length=96)),
                ('issuer', models.CharField(blank=True, default='', max_length=160)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True)),
                ('file_ref', models.CharField(blank=True, default='', help_text='URL/Drive/evidence (no blob).', max_length=512)),
                ('status', models.CharField(choices=[('VALID', 'Vigente'), ('EXPIRING', 'Por vencer'), ('EXPIRED', 'Vencido')], default='VALID', max_length=10)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='fleet.fleetasset')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fleet_documents', to='iam.orgunit')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='fleet.driver')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('asset_class', models.CharField(blank=True, default='', help_text='Clase a la que aplica (moto/liviano/camión/maquinaria/estacionario); vacío = libre.', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_plans', to='iam.orgunit')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_basis', models.CharField(choices=[('KM', 'Por kilómetros'), ('HOURS', 'Por horas'), ('TIME', 'Por tiempo'), ('CONDITION', 'Por condición')], default='KM', max_length=12)),
                ('interval_km', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('interval_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('interval_days', models.PositiveIntegerField(blank=True, null=True)),
                ('severity_factor', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4)),
                ('recommended_action', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='fleet.maintenanceplan')),
            ],
        ),
        migrations.CreateModel(
            name='AssetMaintenanceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_due_km', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('next_due_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('is_due', models.BooleanField(default=False)),
                ('last_done_at', models.DateTimeField(blank=True, null=True)),
                ('last_flagged_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_states', to='fleet.fleetasset')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_states', to='fleet.maintenancerule')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=48)),
                ('name', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('PREVENTIVE', 'Preventivo'), ('CORRECTIVE', 'Correctivo'), ('PREDICTIVE', 'Predictivo')], default='PREVENTIVE', max_length=12)),
                ('trigger_basis', models.CharField(choices=[('KM', 'Por kilómetros'), ('HOURS', 'Por horas'), ('TIME', 'Por tiempo'), ('CONDITION', 'Por condición')], default='KM', max_length=12)),
                ('default_action', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_types', to='iam.orgunit')),
            ],
        ),
        migrations.AddField(
            model_name='maintenancerule',
            name='maintenance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='fleet.maintenancetype'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['company', 'is_active'], name='ix_driver_co_active'),
        ),
        migrations.AddConstraint(
            model_name='driver',
            constraint=models.UniqueConstraint(condition=models.Q(('license_number', ''), _negated=True), fields=('company', 'license_number'), name='uq_fleet_driver_company_license'),
        ),
        migrations.AddIndex(
            model_name='fleetasset',
            index=models.Index(fields=['company', 'asset_type', 'status'], name='ix_asset_co_type_status'),
        ),
        migrations.AddConstraint(
            model_name='fleetasset',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uq_fleet_asset_company_code'),
        ),
        migrations.AddIndex(
            model_name='driverassignment',
            index=models.Index(fields=['asset', 'is_active'], name='ix_driverasg_asset_active'),
        ),
        migrations.AddIndex(
            model_name='driverassignment',
            index=models.Index(fields=['driver', 'is_active'], name='ix_driverasg_driver_active'),
        ),
        migrations.AddIndex(
            model_name='fleetdocument',
            index=models.Index(fields=['company', 'expiry_date'], name='ix_fleetdoc_co_expiry'),
        ),
        migrations.AddIndex(
            model_name='fleetdocument',
            index=models.Index(fields=['company', 'doc_type', 'status'], name='ix_fleetdoc_co_type_status'),
        ),
        migrations.AddConstraint(
            model_name='fleetdocument',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('asset__isnull', False), ('driver__isnull', True)), models.Q(('asset__isnull', True), ('driver__isnull', False)), _connector='OR'), name='ck_fleetdoc_exactly_one_owner'),
        ),
        migrations.AddIndex(
            model_name='maintenanceplan',
            index=models.Index(fields=['company', 'is_active'], name='ix_maintplan_co_active'),
        ),
        migrations.AddIndex(
            model_name='assetmaintenancestate',
            index=models.Index(fields=['asset', 'is_due'], name='ix_maintstate_asset_due'),
        ),
        migrations.AddConstraint(
            model_name='assetmaintenancestate',
            constraint=models.UniqueConstraint(fields=('asset', 'rule'), name='uq_asset_maint_state'),
        ),
        migrations.AddConstraint(
            model_name='maintenancetype',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uq_maint_type_company_code'),
        ),
        migrations.AddIndex(
            model_name='maintenancerule',
            index=models.Index(fields=['plan', 'is_active'], name='ix_maintrule_plan_active'),
        ),
    ]
