# Generated by Django 5.2.12 on 2026-06-13 19:03

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
        ('iam', '0005_approvalrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('TIRES', 'Llantas'), ('INSURANCE', 'Seguro'), ('TOLL', 'Peaje'), ('CLEANING', 'Lavado / limpieza'), ('PERMITS', 'Permisos / circulación'), ('OTHER', 'Otro')], default='OTHER', max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('occurred_on', models.DateField(default=django.utils.timezone.now)),
                ('vendor', models.CharField(blank=True, default='', max_length=160)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='fleet.fleetasset')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fleet_expenses', to='iam.orgunit')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fleet_expenses_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_on', '-id'],
                'indexes': [models.Index(fields=['asset', 'occurred_on'], name='ix_fleetexp_asset_when'), models.Index(fields=['company', 'category'], name='ix_fleetexp_co_cat')],
            },
        ),
        migrations.CreateModel(
            name='FuelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('liters', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('meter_basis', models.CharField(choices=[('ODOMETER_KM', 'Odómetro (km)'), ('HOURMETER', 'Horómetro (h)')], default='ODOMETER_KM', max_length=12)),
                ('meter_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('distance_since_last', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('station_ref', models.CharField(blank=True, default='', max_length=160)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_logs', to='fleet.fleetasset')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fleet_fuel_logs', to='iam.orgunit')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fleet_fuel_logs_created', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_logs', to='fleet.driver')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['asset', 'occurred_at'], name='ix_fuellog_asset_when'), models.Index(fields=['company', 'occurred_at'], name='ix_fuellog_co_when')],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceWorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Abierta'), ('DONE', 'Completada'), ('CANCELLED', 'Cancelada')], default='OPEN', max_length=12)),
                ('description', models.CharField(max_length=255)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('meter_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('parts_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('vendor', models.CharField(blank=True, default='', max_length=160)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='fleet.fleetasset')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fleet_work_orders', to='iam.orgunit')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fleet_work_orders_created', to=settings.AUTH_USER_MODEL)),
                ('maintenance_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='fleet.maintenancetype')),
            ],
            options={
                'ordering': ['-opened_at', '-id'],
                'indexes': [models.Index(fields=['asset', 'status'], name='ix_fleetwo_asset_status'), models.Index(fields=['company', 'opened_at'], name='ix_fleetwo_co_when')],
            },
        ),
    ]
