# Generated by Django 5.2.12 on 2026-06-08 18:46

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0005_employee_party'),
        ('iam', '0005_approvalrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('ESTABLECIMIENTO', 'Establecimiento'), ('MANTENIMIENTO', 'Mantenimiento'), ('SANIDAD', 'Sanidad'), ('COSECHA', 'Cosecha'), ('BENEFICIADO', 'Beneficiado'), ('INFRAESTRUCTURA', 'Infraestructura')], default='MANTENIMIENTO', max_length=24)),
                ('unit', models.CharField(choices=[('JORNAL', 'Jornal'), ('MANZANA', 'Manzana'), ('LATA', 'Lata'), ('QUINTAL', 'Quintal'), ('HORA', 'Hora')], default='JORNAL', max_length=16)),
                ('is_piecework', models.BooleanField(default=False)),
                ('expected_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('default_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finca_labors', to='iam.orgunit')),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, default='', max_length=160)),
                ('area_manzanas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('crop', models.CharField(default='CAFE', max_length=40)),
                ('variety', models.CharField(blank=True, default='', max_length=120)),
                ('planting_year', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plots', to='iam.orgunit')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_label', models.CharField(blank=True, default='', max_length=80)),
                ('planned_date', models.DateField(blank=True, null=True)),
                ('done_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planificada'), ('IN_PROGRESS', 'En proceso'), ('DONE', 'Hecha'), ('CANCELLED', 'Cancelada')], db_index=True, default='PLANNED', max_length=16)),
                ('target_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('jornales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('external_ref', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finca_work_orders', to=settings.AUTH_USER_MODEL)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='iam.orgunit')),
                ('labor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='finca.labor')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='finca.plot')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finca_work_orders', to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='InsumoApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, default='', max_length=64)),
                ('item_name', models.CharField(blank=True, default='', max_length=160)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('unit', models.CharField(blank=True, default='', max_length=24)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='finca.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='FincaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, default='', max_length=120)),
                ('municipio', models.CharField(blank=True, default='', max_length=120)),
                ('zona', models.CharField(blank=True, default='', max_length=160)),
                ('area_manzanas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_headquarters', models.BooleanField(default=False)),
                ('gps_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finca', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finca_profile', to='iam.orgunit')),
            ],
            options={
                'indexes': [models.Index(fields=['zona'], name='finca_finca_zona_ffd853_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='labor',
            index=models.Index(fields=['company', 'category', 'is_active'], name='finca_labor_company_a20d7c_idx'),
        ),
        migrations.AddConstraint(
            model_name='labor',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uq_labor_company_code'),
        ),
        migrations.AddConstraint(
            model_name='labor',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', True)), fields=('code',), name='uq_labor_global_code'),
        ),
        migrations.AddIndex(
            model_name='plot',
            index=models.Index(fields=['finca', 'is_active'], name='finca_plot_finca_i_90d57d_idx'),
        ),
        migrations.AddConstraint(
            model_name='plot',
            constraint=models.UniqueConstraint(fields=('finca', 'code'), name='uq_plot_finca_code'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['finca', 'status'], name='finca_worko_finca_i_7b66a9_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['plot', 'labor'], name='finca_worko_plot_id_b0499d_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['season_label'], name='finca_worko_season__71e872_idx'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.UniqueConstraint(condition=models.Q(('external_ref', ''), _negated=True), fields=('finca', 'external_ref'), name='uq_workorder_finca_extref'),
        ),
        migrations.AddIndex(
            model_name='insumoapplication',
            index=models.Index(fields=['work_order'], name='finca_insum_work_or_924e5d_idx'),
        ),
    ]
