# Generated by Django 5.2.12 on 2026-06-13 19:03

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finca', '0003_insumo_inventory_link'),
        ('iam', '0005_approvalrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FincaBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_label', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('APPROVED', 'Aprobado'), ('ARCHIVED', 'Archivado')], default='DRAFT', max_length=12)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finca_budgets_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finca_budgets_created', to=settings.AUTH_USER_MODEL)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finca_budgets', to='iam.orgunit')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FincaBudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_jornales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('planned_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('planned_insumos_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('planned_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finca.fincabudget')),
                ('labor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='finca.labor')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='finca.plot')),
            ],
        ),
        migrations.AddIndex(
            model_name='fincabudget',
            index=models.Index(fields=['finca', 'status'], name='finca_finca_finca_i_3915ef_idx'),
        ),
        migrations.AddConstraint(
            model_name='fincabudget',
            constraint=models.UniqueConstraint(fields=('finca', 'season_label', 'name'), name='uq_finca_budget'),
        ),
        migrations.AddConstraint(
            model_name='fincabudgetline',
            constraint=models.UniqueConstraint(fields=('budget', 'labor', 'plot'), name='uq_finca_budget_line'),
        ),
    ]
