# Generated by Django 5.2.12 on 2026-03-25 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0004_user_fuel_uom_preference'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userfueluompreference',
            new_name='org_userfue_user_id_f9159c_idx',
            old_name='idx_userfueluompref_user_branch',
        ),
        migrations.RenameIndex(
            model_name='userfueluompreference',
            new_name='org_userfue_branch__298934_idx',
            old_name='idx_userfueluompref_branch',
        ),
    ]
